### ISSUE TITLE
Theme installer

### ISSUE THREAD

**Issue by xAlina02** [rozniak/xfce-winxp-tc#109]
Hello, sorry for the inconvenience, I would like to ask, if there would be the possibility of making an installer to install the entire Windows XP theme as it happens in the Chicago95 Windows 95 theme.
I am a person who barely knows about linux and its environment and programming, but the Windows XP theme that you do is incredible and it would be great to have it, I tried to install it on my own but I did not advance anything, because and it will be funny, I did not understand anything.
Hence, my idea of ​​a theme installer for people new to linux like me, and others.

**Comment by rozniak** [comment]
Hey!

There is an open issue regarding development of an installation wizard: #81 

I do hope to try and replicate the Windows XP setup process, however I'm not sure when that'll be. At the moment I'm still working on themes, and there's a number of things that probably should be prioritised first before the setup wizard (supporting other package formats, logonui LightDM greeter, shut down dialogs etc.)

I wish I could get it done sooner, it's a bit daunting with how much there is to do and it seems like people are finding this project from somewhere? I do have user-friendliness in mind, especially for people with less experience with Linux, so it sucks to disappoint people at the moment that I haven't progressed that far yet.

All I can say for now I suppose is keep an eye on this repository, and in particular issue #81 as that'll be where the setup wizard work is done when I get around to it. :smile:

**Comment by xAlina02** [comment]
Thank you for the response, and thank you for the concern about the problem!
How I said in the previous message, I like this theme and how it is developing.
I will be reviewing the evolution from time to time and about all the sections that you told me.
