### ISSUE TITLE
Add the Royale Theme

### ISSUE THREAD

**Issue by xmha97** [rozniak/xfce-winxp-tc#118]
Windows XP Media Center Edition (MCE) is a version of the Windows XP operating system.
MCE default theme is "Royale"
Please add this theme.
![image](https://user-images.githubusercontent.com/23485114/158168417-efdb4977-6bbe-4d5c-963e-2d809b258e0d.png)

**Comment by rozniak** [comment]
Hey - I do plan to work on Royale, it's currently located under `/themes/symphony/royale`. It's the XFWM4 theme only for now, I have an issue to complete the rest of the theme: #10
