### ISSUE TITLE
Start menu needs localization

### ISSUE THREAD

**Issue by AliAndalus** [rozniak/xfce-winxp-tc#135]
Hello, I would like to ask something, for people who speak other languages, is there a possibility to change the text of the "start" button and the content of start menu (like “My Documents” or “Control Panel”) to put it in another language? In the event that it is not possible, how difficult would it be to implement that possibility? I mention this because I am not a native English speaker and I like to have a linguistic harmony and not an amalgamation of languages ​​in the same system.
I hope this question does not bother you too much, thank you.

**Comment by rozniak** [comment]
Hello!

I have it in mind to replace the hard-coded English strings with localised versions through `.po` files. I've not done this before so it might take me a bit to have a look at how this can be implemented.

**Comment by AliAndalus** [comment]
Hello, thank you very much for the answer, I am glad that you have ambition with my request :)

**Comment by rozniak** [comment]
Out of interest, what language do you need? I will get an XP installation in your language so I can get the translations as a test.

**Comment by AliAndalus** [comment]
I speak spanish, I am from Spain, so I need the traditional sort of Spanish.

**Comment by AliAndalus** [comment]
Sorry for late reply.

**Comment by rozniak** [comment]
Starting this work in #96 

For this particular issue, it will probably be necessary to shift out some of this localisation to a separate library. This refers to strings such as `My Computer` and `Control Panel` which are used all over the system in Windows so the localisation for those cannot live in the Start menu source code.

**Comment by AliAndalus** [comment]
Okay, thanks for worrying, and sorry for the inconvenience :)

**Comment by rozniak** [comment]
@AliAndalus Sorry it's taken so long honestly, the scripts were a bit of a nightmare to write. You might be happy to see some actual progress from today:
![image](https://user-images.githubusercontent.com/13258281/179096552-7de604d0-c854-4cfc-8969-5d530e6524a2.png)

The only problem is that my MUI sources seem to be RTM and are thus missing `xpsp1res.dll.mui` (hence `Set Program Access and Defaults` is still in English). I'll see if I have time tomorrow to see if there's SP1/SP2/SP3 ISOs, really SP2 would probably sort out the vast majority of missing strings though for this only SP1 is needed.

**Comment by rozniak** [comment]
I have located the DLLs inside SP2 (will check SP3 later). They are listed inside the INF that describes all the files to copy (`<root>/i386/update/update.inf`) under sections such as `[CopyAlways.Prf.Mui.0401.Files]`.

The MUIs for `xpsp1res.dll` are `ip/spra<langcode>.dll`, `xpsp2res.dll` is `ip/sprb<langcode>.dll`, and `xpob2res.dll` is `ip/obrb<langcode>.dll`.

Was a real pain to find this but the digging prevailed. I'll check SP3 and then will need to include this in the locale tools (`muiprep.sh`).

**Comment by rozniak** [comment]
These do exist on the XP SP3 ISO (full XP install), SP3 is `sprc<langcode>.dll` (predictable).

Will update `muiprep.sh` to ensure these files are moved out of the SP3 dir into their respective MUI dirs where they belong.

**Comment by rozniak** [comment]
Work done, just going to clean up and merge.
![image](https://user-images.githubusercontent.com/13258281/180082635-92a4db14-c16d-4f9f-8e65-b94462662cf2.png)
