### ISSUE TITLE
wintc-exec can't install

### ISSUE THREAD

**Issue by EspadaRunica** [rozniak/xfce-winxp-tc#143]
can't i install wintc-exec

debian bullyese

"Can't find library: wintc-exec.h."

**Comment by EspadaRunica** [comment]
I thought that when installing wintc-comgtk.h I would also have to install wintc-exec but no, it's just "exec"

**Comment by rozniak** [comment]
The `README` under `/packaging/deb/libs` should explain how to install these libraries :grin:
