### ISSUE TITLE
Not appear plugins of xfce4

### ISSUE THREAD

**Issue by Deltahh** [rozniak/xfce-winxp-tc#144]
I installed everything correctly and successfully, each .desktop file was installed in the corresponding place, but the plugins to add to the xfce4 panel do not appear, only the default ones appear

**Comment by rozniak** [comment]
@Deltahh Sorry I took a while to get back to you - can you run the commands and compare the output on your end with this screenshot:
![image](https://user-images.githubusercontent.com/13258281/172602049-438420d6-226d-4372-9a7c-3bbab1a62a0b.png)

Should hopefully see the `.so` files for the Start menu and tray in there?

**Comment by Deltahh** [comment]
No problem, all the effort you made to create this is greatly appreciated, it's spectacular!
Look, I leave you the image
![2022-06-08_10-53](https://user-images.githubusercontent.com/28799086/172634729-0e400093-7138-45bc-8738-558cdde895d1.png)
.

**Comment by rozniak** [comment]
Do plugins like the Whisker Menu or PulseAudio Plugin show up when you go to add them to the panel?

**Comment by rozniak** [comment]
Closing abandoned issue
