### ISSUE TITLE
Can't build systray or start 

### ISSUE THREAD

**Issue by steven2024** [rozniak/xfce-winxp-tc#146]
cp: cannot stat '/home/unix/xfce-winxp-tc-master/shell/systray/build/systray': No such file or directory
cp: cannot stat '/home/unix/xfce-winxp-tc-master/shell/start/build/start': No such file or directory
When doing ./packprog.sh shell/(*program*)

**Comment by rozniak** [comment]
Was the build successful? It would make sense for the `cp` to fail if the `make` failed beforehand and didn't output a binary. Can you post the full output of the log files?

**Comment by steven2024** [comment]
[shell-systray-build.log](https://github.com/rozniak/xfce-winxp-tc/files/8979918/shell-systray-build.log)
[shell-start-build.log](https://github.com/rozniak/xfce-winxp-tc/files/8979919/shell-start-build.log)

* Failed to copy files for shell/(program-name) *

**Comment by rozniak** [comment]
Ohhh no I see what's happened here, someone else did the same thing. You need to use `packplug.sh` to build and package `shell/systray` and `shell/start` - they're XFCE panel plugins, not programs. :+1:

**Comment by steven2024** [comment]
Thanks! I now understand what I did wrong.

**Comment by steven2024** [comment]
I already did them anyways then. When I saw them with the programs I thought there we something else than the panel (which I already did build before that)

**Comment by steven2024** [comment]
![image](https://user-images.githubusercontent.com/89735533/175651706-20ba1b9e-61ba-44d1-8548-70af85835925.png)

**Comment by rozniak** [comment]
Think this issue is resolved
