### ISSUE TITLE
Incomplete and buggy theme

### ISSUE THREAD

**Issue by josemiguex** [rozniak/xfce-winxp-tc#151]
Hello, I'm using Linux mint 21 xfce, I installed everything (icons, cursor, theme, panel...) the problem it's that the theme looks buggy and incomplete 
![Captura de pantalla_2022-08-08_10-22-35](https://user-images.githubusercontent.com/22611815/183373718-67cb71b0-d4f4-4bb9-b1a6-aeb85802b062.png)

I'm missing something?

Thanks!!!

**Comment by rozniak** [comment]
That looks like loads of the image files are missing for some reason, what does `/usr/share/themes/Windows XP style (Blue)/Resources` look like?

**Comment by rozniak** [comment]
Also is this on the latest `master`? There should be Spanish language support for the Start menu... :thinking:

**Comment by josemiguex** [comment]
Yeah, I'm using the latest master

I fixed the problem, my user didn't have access to the theme folder, now it's working without problems!

I installed everything except the locale, I'm going to install it now

Two things:

In the windows button item,when I click on the bottom It doesn't do anything,  there's a little margin there
![Captura de pantalla_2022-08-08_13-39-03](https://user-images.githubusercontent.com/22611815/183410008-753c13c8-77bf-4c1d-9d2b-1b1e9814ecbf.png)

In the notification area item,only the clock appears, without any icon (as I see in the screenshots this is normal right?)

Thanks!

**Comment by rozniak** [comment]
> I installed everything except the locale, I'm going to install it now

Locale isn't a separate thing to install... the Start menu should include translations by default. It might be something I need to test on Linux Mint - I'll get an install going later to check this. :eyes: 

> In the windows button item,when I click on the bottom It doesn't do anything, there's a little margin there (I don't remember if this is how it works on Windows XP)

I never thought about this but you're quite right it should activate the window button even if you click in the margin - I have just opened #152 to work on that at some point. Thanks for bringing this up! :grin: 

> In the notification area item,only the clock appears, without any icon (as I see in the screenshots this is normal right?)

Yes, at the moment I have only implemented the clock for the notification area.

**Comment by rozniak** [comment]
I officially have no idea why the locales do not work on Linux Mint, I've installed it in Spanish and had a poke around. The Run dialog is in Spanish but the Start menu is not. It works fine on Debian I am not sure what Mint is doing differently.

**Comment by rozniak** [comment]
Locale problem opened as #153 

Will close this issue as the core problem is resolved - the additional problems now have their own issues. :+1:

**Comment by josemiguex** [comment]
For now the language problem I just set the system language to English to look consistent

I like having the battery, wifi.etc icons in the panel, even if the notification area didn't include the icons it would be nice to at least the icons looks consistent with the theme using the status tray or power manager plugin
![Screenshot_2022-08-09_08-44-45](https://user-images.githubusercontent.com/22611815/183582354-5f6e7efe-ee5d-4ed8-820b-9297a8e41349.png)

Thanks

**Comment by rozniak** [comment]
> I like having the battery, wifi.etc icons in the panel, even if the notification area didn't include the icons it would be nice to at least the icons looks consistent with the theme using the status tray or power manager plugin

This will get fixed when the theme work on #13 is merged. :sunglasses:

**Comment by josemiguex** [comment]
How I can for now manually change the icons? I'm fine with icons like this:

![Screenshot_2022-08-09_11-45-30](https://user-images.githubusercontent.com/22611815/183618674-3172832e-226b-4fb3-b9ef-da92e10acdfc.png)

Thanks

**Comment by rozniak** [comment]
> How I can for now manually change the icons?

If you want them to be rendered in the correct colour, I think you need to insert the following SCSS between line 29 and 30 in `/themes/gtk-3.0-base/override/xfce-panel.scss`:

```
& > *
{
    color: #FFFFFF;
}

& menuitem
{
    color: $fg_color;
}
```

Then obviously rerun `./packthem luna/blue` and install the package.

**Comment by josemiguex** [comment]
Thanks, it worked (well, didn't change the battery icon color so i have to modify the /gtk-3.0/gtk.css file to change the color)
