### ISSUE TITLE
How on earth do you install this?

### ISSUE THREAD

**Issue by linlinxza** [rozniak/xfce-winxp-tc#159]
Really... How?

**Comment by rozniak** [comment]
There are scripts under the `/packaging` dir that compile and output .deb packages that you can install using `dpkg`. Have a look at the `README`s they should explain the usage. :smile:

**Comment by linlinxza** [comment]
Okay. But now I am having this issue:

-- Checking for module 'wintc-exec'
--   No package 'wintc-exec' found

**Comment by rozniak** [comment]
That is because you need to install the libraries under `/shared` first. :sunglasses:

**Comment by rozniak** [comment]
Closing this now, if you still need help just reply and I'll be happy to reopen to assist. :smiley:

**Comment by linlinxza** [comment]
> Closing this now, if you still need help just reply and I'll be happy to reopen to assist. 😃

It would be much easier if things were already compiled. Anyway, I think I'll just keep Zorin OS Lite as it is. If I want a sort of XP look, I'll just use KDE Plasma where changing themes is easier. lol

**Comment by rozniak** [comment]
> It would be much easier if things were already compiled. Anyway, I think I'll just keep Zorin OS Lite as it is. If I want a sort of XP look, I'll just use KDE Plasma where changing themes is easier. lol

In future there should be an actual compiled 'release', manually compilation is necessary at the moment because there is still so much to do.

**Comment by linlinxza** [comment]
Fair enough. Well, it looks good. It just needs to be easier to set up.

**Comment by The-WindowsVista** [comment]
I compiled all of it, excluding the icon theme, which I also merged with b00merang's icon theme, and included the backgrounds if you want it.

**Comment by linlinxza** [comment]
> I compiled all of it, excluding the icon theme, which I also merged with b00merang's icon theme, and included the backgrounds if you want it.

Sure. I might try it out in a VM.
