### ISSUE TITLE
Cannot change how start and systray look

### ISSUE THREAD

**Issue by siladitya-basu** [rozniak/xfce-winxp-tc#161]
![image](https://user-images.githubusercontent.com/22571287/199501544-cf0ceacf-72e6-4db6-bb71-650ae8e9cc8f.png)

After installing the necessary dependencies and running

`./packplug.sh shell/start shell/systray`

And then using

`sudo dpkg -i <xxx-yyy-plugin.deb>`

I'm still not getting the XP look for Start and the systray.

I'm running Xubuntu on VirtualBox.

**Comment by rozniak** [comment]
Looks to me like you are not using the panel plugins - the Start menu and systray are installed as new plugins. You need to edit the items in your panel to add them.

Also to get rid of the grey background you must install the xfce4-panel fork under `/submodules`

**Comment by siladitya-basu** [comment]
![image](https://user-images.githubusercontent.com/22571287/199558072-218387aa-05fb-4daf-9761-da95ab157917.png)


Followed the Readme in `/submodules`, which got rid of the grey background, and then added the Start menu and systray as panel plugins. Thanks!

You have an awesome project going on here!

**Comment by rozniak** [comment]
Have you set a solid colour for the panel background? If you set it to 'Use system theme' or whatever it should get the blue gradient applied correctly. And install the fonts package so that you have the right font style for the Start button's text. 😁

**Comment by siladitya-basu** [comment]
Hi @rozniak! Glad to see this project making progress. I decided to return to this and theme my Linux Mint installation. I was happy to see that the packaging has improved a lot, and it is now so much easier to install!

Wanted to ask two things:
1. Where do I get the blue Luna background for the panel?
2. The systray and start menu are not appearing in the panel items list, even after I installed the appropriate `.deb` package in `./xptc` after building. Do I have to install anything else?

**Comment by rozniak** [comment]
The answer to both your questions is the same - the project no longer uses XFCE Panel plugins. They were rolled into a single program for the complete taskband - `wintc-taskband`. If you run that, everything will show up.

As not everything is implemented yet (notably the volume icon for instance), you may still want to keep an XFCE panel docked somewhere with these missing bits for now. :grin:

**Comment by siladitya-basu** [comment]
Ran the program and got a beautiful looking taskbar. Thank you!
