### ISSUE TITLE
 Panel broke after update

### ISSUE THREAD

**Issue by IntoTheVoid-900** [rozniak/xfce-winxp-tc#167]
I set this up on Xubuntu yesterday, and I just `sudo apt upgrade`ed my system to find the panel is now broken. Help?
![image](https://user-images.githubusercontent.com/74509183/212579077-006b8be1-5ca8-4fb8-919b-9536a04d8de9.png)

**Comment by rozniak** [comment]
You simply need to repackage and install `libxfce4-panel` from the fork. :grin:

**Comment by IntoTheVoid-900** [comment]
I reinstalled the panel and it worked for another day, but then the next update broke it again.

**Comment by rozniak** [comment]
It will get overwritten if `libxfce4-panel` gets updated from upstream, yes.

**Comment by rozniak** [comment]
Closing old issue as question answered
