### ISSUE TITLE
Build requirements on 23.04 lunar lobster

### ISSUE THREAD

**Issue by blue-devil-93** [rozniak/xfce-winxp-tc#169]
sudo apt-get install cmake pkg-config libgarcon-1-dev devhelp libgtk-3-dev libgarcon-gtk3-1-dev libxfce4panel-2.0-dev

inside packaging/libs
./packlibs.sh comgtk
sudo dpkg -i *.deb
./packlibs.sh exec
sudo dpkg -i *.deb
./packlibs.sh shllang
sudo dpkg -i *.deb
inside packaging/panel 
./packplug.sh shell/start 
./packplug.sh shell/systray
sudo dpkg -i *.deb
![screenshot-rory](https://user-images.githubusercontent.com/59343188/233786519-43a7d33f-4e84-4cd8-a523-857a4803b874.png)

**Comment by rozniak** [comment]
#192 introduced `chkdeps.sh` for identifying missing dependencies on system, should be simple going forward
