### ISSUE TITLE
How to change shortcuts?

### ISSUE THREAD

**Issue by blue-devil-93** [rozniak/xfce-winxp-tc#170]

**Comment by blue-devil-93** [comment]
![shortcuts](https://user-images.githubusercontent.com/59343188/233786998-4b5d2d12-8ea8-4911-afc8-825fb2818049.png)
I mean those.
On my pc the folders for images etc. have different names due to localizations. And i would like to link the search tool to the mate search tool etc.

**Comment by rozniak** [comment]
The translations come from Windows - they reside under the `libwintc-shllang` library (under `/shared/shllang`  in this repo). If you want to adjust the translations, use `poedit`, and edit your locale under `/shared/shllang/po`.

The links themselves activate 'actions' (function `wintc_launch_action` in `libwintc-exec`, under `/shared/exec` in this repo). You can add `case WINTC_ACTION_SEARCH:` with your desired command line into the `switch` here: https://github.com/rozniak/xfce-winxp-tc/blob/master/shared/exec/src/action.c#L18

I hope this helps! :grin:

**Comment by blue-devil-93** [comment]
Thanks its exactly tbe file i would need to edit.
Once i got the time to try it ill send you what i did edit, maybe its of
use for others too.

Maybe you can link file search to catfish. Yes its optically not ideal but
at least its better than not implemented.
 The other thing i ll  do some experiments how i get it to open Picture
folders etc. I suppose you have to for example run:
exo-open --launch FileManager $XDG_PICTURES_DIR

Maybe even someting like this:
https://askubuntu.com/questions/457047/how-can-i-get-the-xdg-default-user-directories-from-python

**Comment by blue-devil-93** [comment]
exo-open --launch FileManager $(xdg-user-dir PICTURES)

works on bash. Need to check if it also works within the C file..

**Comment by rozniak** [comment]
Oh I see what you mean, `~/Pictures` (and other dirs) are translated on the file system for other languages? I overlooked that when I wrote the code, I would consider that a bug that needs to be fixed in this repo.

NTS look at https://docs.gtk.org/glib/enum.UserDirectory.html

**Comment by rozniak** [comment]
> Maybe you can link file search to catfish. Yes its optically not ideal but at least its better than not implemented.

Best to compile this change on your local machine - can't assume the user will have catfish installed, I hadn't heard of it until now myself. I think 'not implemented' is fine because that is the true state of the component.

**Comment by blue-devil-93** [comment]
[exo-patched.zip](https://github.com/rozniak/xfce-winxp-tc/files/11303064/exo-patched.zip)

soon im adding a gif file of what it does

**Comment by rozniak** [comment]
I will raise a bug this evening to bugfix the XDG paths in wintc_launch_action

**Comment by rozniak** [comment]
@blue-devil-93 I have pushed a fix for XDG paths in `wintc_launch_action`, please pull from `master` and let me know if your problem is resolved. :grin:

**Comment by blue-devil-93** [comment]
Looking at the source code from the pushed fix, you have found a very good
solution.
thunar and caja has an "recently used" virtual folder in ubuntu 23.04. As
well as the computer can be linked  to drive overview instead of /.
Look at your fix next days.

**Comment by rozniak** [comment]
Closing as issue should be resolved
