### ISSUE TITLE
Fail to build package for ./packthem.sh luna/blue

### ISSUE THREAD

**Issue by spamman63** [rozniak/xfce-winxp-tc#174]
I'm following this guide exactly as done on screen and at https://youtu.be/wKZqrG9GrdI?t=1463 and when he does

./packthem.sh luna/blue

It builds successfully, however when I attempt to do this it reads 

[ 33%] Built target venv-setup
[ 66%] Generating composed
Traceback (most recent call last):
  File "/home/username/Documents/xfce-winxp-tc/tools/bldtheme/bldtheme.py", line 6, in <module>
    from PIL import Image, ImageDraw
ModuleNotFoundError: No module named 'PIL'
make[2]: *** [CMakeFiles/resources-gtk2.dir/build.make:73: composed] Error 1
make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/resources-gtk2.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
dpkg-deb: error: failed to open package info file '/home/username/Documents/xfce-winxp-tc/packaging/deb/themes/build/out/DEBIAN/control' for reading: No such file or directory
Failed to build package for luna/blue, moving on...

I'm not sure what to do here, I did

sudo apt install python3-pil

successfully but it didnt change anything. I'm doing this on a new install of Pop OS after installing XFCE

**Comment by rozniak** [comment]
Hi - I am currently out and about at the mo, I'll investigate the build on Pop! OS when I'm back at my computer. 😁

**Comment by rozniak** [comment]
I have just tried it out on Pop! OS, it seemed to work fine. Are you perhaps missing package `python3-venv`?

This is what I see:
![image](https://user-images.githubusercontent.com/13258281/235451731-7930e50f-dfe1-4e95-91f1-5653dddf2967.png)

By the way, that video is slightly old. You can also build Windows Classic and Watercolor/Professional now with:
`./packthem.sh native professional luna/blue`
and install the outputted packages.

**Comment by rozniak** [comment]
Thanks for the info - I guess the question is why the CMake plowed on despite the venv not building. I'll probably give it a look whilst I work on #140

**Comment by Villagerjj** [comment]
> What fixed it for me was installing python3-venv and then deleteing from xfce-winxp-tc/tools/bldtheme/.venv

that helped me get slightly farther.

for the developer:

./xfce-winxp-tc/packaging/deb/themes/packthem.sh luna/blue
[ 33%] Generating /home/john/Documents/xfce-winxp-tc/tools/bldtheme/.venv
Collecting pillow
  Using cached Pillow-9.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
Installing collected packages: pillow
Successfully installed pillow-9.5.0
[ 33%] Built target venv-setup
[ 66%] Generating composed
[ 66%] Built target resources-gtk2
[100%] Generating gtk.css
make[2]: SASS-NOTFOUND: No such file or directory
make[2]: *** [CMakeFiles/theme-gtk3.dir/build.make:74: gtk.css] Error 127
make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/theme-gtk3.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
dpkg-deb: error: failed to open package info file '/home/john/Documents/build/out/DEBIAN/control' for reading: No such file or directory
Failed to build package for luna/blue, moving on...

**Comment by spamman63** [comment]
![Screenshot_2023-05-10_02-32-32](https://github.com/rozniak/xfce-winxp-tc/assets/77785719/7f29e123-d220-4cb7-b4ee-1b143af2d567)


I've installed python3-venv, which wasn't installed before, to encounter the exact same error unchanged

**Comment by rozniak** [comment]
You most likely need to bin `/tools/bldtheme/.venv` because the directory itself is the dependency - if the folder exists then the target will not run.

**Comment by spamman63** [comment]
> You most likely need to bin `/tools/bldtheme/.venv` because the directory itself is the dependency - if the folder exists then the target will not run.

That worked, I didn't know there were hidden files so I did ctrl-h and deleted .venv and it built, thanks

**Comment by rozniak** [comment]
Glad to have helped. :grin:
