### ISSUE TITLE
Button images should be removed

### ISSUE THREAD

**Issue by rozniak** [rozniak/xfce-winxp-tc#19]
Icons/images on standard `GtkButton` widgets should be removed as buttons didn't natively support this in Windows XP - it looks out of place and Linux-y.

**Comment by paulsapps** [comment]
This is a P1 issue

**Comment by rozniak** [comment]
Need to consider that this should only apply on standard buttons - toolbar buttons should retain their icons/images.

**Comment by rozniak** [comment]
Had a thought about this - potentially doable if we can apply a CSS sibling selector on the text. ie. select text, find icon sibling and set `display: none;`. This should mean buttons either have an image, or they have text, not both (akin to XP I think...)

**Comment by rozniak** [comment]
I know more about GTK and theming nowadays - I've removed the `good-first-issue` label because actually this is most likely impossible via theming.

If this is ever implemented, it would be in the form of a hack/forked version of GTK itself.

**Comment by rozniak** [comment]
This issue will never be fixed as there cannot be a generic solution to the problem - it should become less noticeable once more programs are included within this repo.
