### ISSUE TITLE
Arch linux questions

### ISSUE THREAD

**Issue by JHudd435** [rozniak/xfce-winxp-tc#193]
I have xfce and i3 installed on arch linux. Will installing this mess with my i3 setup?

**Comment by rozniak** [comment]
I don't see why it would, nothing in here messes with your system configuration - all that happens is programs/themes are installed and then you have the choice of using them or not.

**Comment by JHudd435** [comment]
Do I have to make install every component?

**Comment by rozniak** [comment]
On Arch? Yeah at the moment, cos I'm still working on merging #190

**Comment by JHudd435** [comment]
About how long until that's merged? I'll wait if it isnt long

**Comment by JHudd435** [comment]
I went ahead and installed https://aur.archlinux.org/packages/xfce-winxp-tc-git from the aur. The taskbar and whisker menu look almost the same as before, but buttons look like xp. Icons are also xp, but some of them are blurry. How do I change the whisker menu and taskbar?

**Comment by JHudd435** [comment]
Nvm, got everything set up.

**Comment by toprak** [comment]
@JHudd435 hey mate, may I ask you how did you do that? i could not set whisker menu and taskbar

**Comment by rozniak** [comment]
This project doesn't touch the Whisker menu - there is a separate program installed that replaces the panel entirely. Run `wintc-taskband`

**Comment by JHudd435** [comment]
And remove the old taskbar and whisker menu, otherwise it'll just lay on top

**Comment by toprak** [comment]
thank you guys

**Comment by toprak** [comment]
@rozniak so basically I just have to set 'wintc-taskband` and `wintc-desktop' as startup applications, and choose styles from window manager settings and appearence settings right? do I miss something i just want to set this up fully

**Comment by rozniak** [comment]
Yeah, though it's up to you if you want to remain using `xfdesktop` for the time being - `wintc-desktop` is extremely early and just has the code in it to create the desktop window with nothing in it.
