### ISSUE TITLE
Start menu, taskbar questions

### ISSUE THREAD

**Issue by JHudd435** [rozniak/xfce-winxp-tc#195]
Where is the start menu config file located? I'd like to delete and add some shortcuts

**Comment by rozniak** [comment]
The contents are static at the moment, and populated by the two files:

`/shell/taskband/res/all.menu` -- currently used for the MFU list, pretty much just all desktop entries minus settings
`/shell/taskband/res/start-menu.menu` -- used by the *All Programs* list to organise desktop entries by category

The MFU, customising *All Programs*, and pins are all TODO

**Comment by JHudd435** [comment]
Is there a quick launch toolbar or is that not implemented yet?

**Comment by rozniak** [comment]
There isn't yet, there is quite a bit that needs doing with the taskband, it's heavily WIP.

**Comment by JHudd435** [comment]
Is there a shortcut key for the start menu?

**Comment by rozniak** [comment]
Hm didn't you ask that already ? #86 ?

**Comment by JHudd435** [comment]
I thought maybe it was just the super key that didn't work. Sorry.
