### ISSUE TITLE
Conflict for notepad with wine

### ISSUE THREAD

**Issue by SelfRef** [rozniak/xfce-winxp-tc#202]
The default `notepad` binary name at `/usr/bin/notepad` has name collision with notepad from [`wine`](https://archlinux.org/packages/multilib/x86_64/wine/). At least on Arch Linux, not sure about Debian. Probably the only option would be to change the name to be unique because it can be a common case to have `wine` already installed.

**Comment by rozniak** [comment]
Sugar, wine on Arch comes with a `notepad`? On Debian it doesn't, you just get `wine` and some of the utils (`regedit`).

Kind of a pickle, because I named it `notepad` so that you could launch it identical to Windows :weary:

**Comment by SelfRef** [comment]
Yeah. I was a little surprised when looked in Debian package and I didn't see a `notepad` binary in tree. Is it probably somewhere else in separate package? Or not at all? There is a full [files tree](https://archlinux.org/packages/multilib/x86_64/wine/files/) for Arch.

> Kind of a pickle, because I named it `notepad` so that you could launch it identical to Windows 😩

Hmm, at least `notepad.exe` is still free to use. Not canonical for Unix but still available option.

**Comment by lili1228** [comment]
Every Wine comes with Notepad, it's just that Arch has a glorified symlink to `wine notepad` in /usr/bin

**Comment by rozniak** [comment]
Mmmm I'm really not keen on `notepad.exe`... if anything the WINE one should be called that, no? :sweat_smile: 

Not sure atm

**Comment by SelfRef** [comment]
For compatibility purposes [I've changed](https://aur.archlinux.org/cgit/aur.git/commit/?h=xfce-winxp-tc-git&id=11ed1e22b7d759f0f38b6572fc4c4997191e98eb) to `wintc-notepad` in AUR version. I wonder if other distros also have this symlink to notepad. If not, then it's only Arch-related.

**Comment by rozniak** [comment]
I think as part of the porting process need to check if this symlink for `notepad` exists when WINE is installed on the target distro. For the distros that have this sadly there is no choice but to use `wintc-notepad` really is there?

If so, I would probably suggest:
- Do not set the `OUTPUT_NAME` change for the distro (basically wrap in `if (NOT ${WINTC_PKGMGR STREQUAL "archpkg")` here https://github.com/rozniak/xfce-winxp-tc/blob/master/windows/notepad/CMakeLists.txt#L43 ) 
- `notepad.desktop` will need to become `notepad.desktop.in` and `configure_file`'d first with this name as the executable (I think `@OUTPUT_NAME_WINTC_NOTEPAD@` will work?)

**Comment by rozniak** [comment]
Have resolved this, for `archpkg` the output executable will be `wintc-notepad`. Will test this on a case-by-case basis in future when porting to check whether `notepad` will clash, and not rename the target if so.

Thanks again for your testing and patience @SelfRef !

**Comment by SelfRef** [comment]
Thanks again for the fix!

The solution with checking if wine symlink is in the filesystem wouldn't work because if user would install `xfce-winxp-tc` and then `wine` package then `wine` installation would fail. Conditional name is probably the best solution as in your fix.
