### ISSUE TITLE
Create logonui LightDM greeter

### ISSUE THREAD

**Issue by rozniak** [rozniak/xfce-winxp-tc#205]
This issue is to track the creation of the logonui LightDM greeter. Specifically this is for implementing the user-friendly 'Welcome' greeter.

Other notes to consider:
- Support waving Windows flag as ini option?
- Support entry point for OOBE, I think this needs to be in the greeter for first run...

**Comment by rozniak** [comment]
I have made a fair bit of progress on this. Main thing I need to focus on atm is the 'fit and finish' for the logon screen, fade in effect for the logo, fading user entries when hovering over one - that sort of thing.

![image](https://github.com/rozniak/xfce-winxp-tc/assets/13258281/99a0792f-38f7-459e-bec7-fca4ed7162e1)

**Comment by rozniak** [comment]
I'm going to merge this work for now, and sort the remainder later. There's style stuff, and rough edges to polish, but really I need to do some experimenting with custom GTK widgets and learn things to do this properly. Currently it works and is a decent start, albeit with hacks.

![image](https://github.com/rozniak/xfce-winxp-tc/assets/13258281/3231a192-b15e-4a34-9621-9dedfdeed2c5)

![image](https://github.com/rozniak/xfce-winxp-tc/assets/13258281/304bcb27-ddf3-48c3-a600-ec85124da86b)

![image](https://github.com/rozniak/xfce-winxp-tc/assets/13258281/1d7dda7f-39bd-4e1b-a340-92e24ec0b8b6)

**Comment by MrMegarich** [comment]
Sick, keep it up!

**Comment by dginovker** [comment]
Wow that look good
