### ISSUE TITLE
How can I obtain the startmenu.desktop file?

### ISSUE THREAD

**Issue by Mibanfi** [rozniak/xfce-winxp-tc#218]
Hello,
When I install the package, either through the .sh file or the aur package (I'm on Arch), it doesn't seem to generate the startmenu.desktop file. In fact, I've checked my panel plugins folder in the filesystem, and I can confirm it isn't there. I even did a system-wide search with the `sudo find` command, but it doesn't give any results. Where can I find the startmenu.desktop file in the source code? I would like to install the plugin manually, since everything else works fine.
Thank you in advance!

**Comment by rozniak** [comment]
You can't find it, because it doesn't exist. :grin: 

There are no panel plugins anymore, they were replaced by a single program - launch `wintc-taskband` to get the Start menu/taskbar/systray panel.

**Comment by Mibanfi** [comment]
Thank you so much! You saved me.
One more question before we mark this as completed- when I run `wintc-taskband`, I get an error message saying `libxfce4windowing not available.` Do you have an idea how I could solve this?

**Comment by rozniak** [comment]
That's not an error, it's a warning. If the taskband started it's fine - it attempts to dynamically load either libxfce4windowing, or libwnck at runtime for doing window management.

**Comment by Mibanfi** [comment]
Oh, I see now! Thank you so much for everything! I'm very grateful
