### ISSUE TITLE
The Panel Doesn't have the them applied on mint-xfce

### ISSUE THREAD

**Issue by MrMegarich** [rozniak/xfce-winxp-tc#232]
The windows borders and the icons are fine, but I can't change the start menu, or the panel.

**Comment by rozniak** [comment]
Are you running `wintc-taskband` ?

**Comment by MrMegarich** [comment]
what is that?

I just ran build-all in packaging

**Comment by MrMegarich** [comment]
then i applied the theme in appearance settings

**Comment by rozniak** [comment]
`wintc-taskband` provides the taskbar, Start menu and notification area. This repo no longer produces plugins for XFCE panel.

**Comment by MrMegarich** [comment]
Where do I get Wintc-taskband?

**Comment by rozniak** [comment]
It's one of the programs included by `buildall.sh` - if you close XFCE Panel with `xfce4-panel -q` you can run `wintc-taskband` to launch the taskbar.

If you want it to run at log on you need to add it to XFCE Startup items in the Session settings atm.

**Comment by MrMegarich** [comment]
Dude thank you so much! Good luck with the rest of the project!
