### ISSUE TITLE
says libgdk-pixbuf-2.0-0 isn't installed, even though it is

### ISSUE THREAD

**Issue by chaogamer** [rozniak/xfce-winxp-tc#235]
im trying to package winbrand, but i keep getting this error

```
$ sudo dpkg -i libwintc-winbrand.deb
[sudo] password for winme11:          
Selecting previously unselected package libwintc-winbrand.
(Reading database ... 365622 files and directories currently installed.)
Preparing to unpack libwintc-winbrand.deb ...
Unpacking libwintc-winbrand (1.0) ...
dpkg: dependency problems prevent configuration of libwintc-winbrand:
 libwintc-winbrand depends on libgdk-pixbuf-2.0-0; however:
  Package libgdk-pixbuf-2.0-0 is not installed.

dpkg: error processing package libwintc-winbrand (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libwintc-winbrand
```

but then when i check, it's already is installed
```
`$ sudo apt install libgdk-pixbuf2.0-0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgdk-pixbuf2.0-0 is already the newest version (2.40.0+dfsg-3ubuntu0.4).
The following packages were automatically installed and are no longer required:
  cinnamon-common cjs exo-utils gir1.2-caribou-1.0 gir1.2-cmenu-3.0
  gir1.2-keybinder-3.0 gir1.2-meta-muffin-0.0 gir1.2-nemo-3.0
  gir1.2-timezonemap-1.0 libcaribou-common libcaribou0 libcjs0
  libkeybinder-3.0-0 libmozjs-52-0 libnemo-extension1 libtimezonemap-data
  libtimezonemap1 metacity-common nemo nemo-data `

```

how do i make it stop doing this so i can install the packages?

**Comment by rozniak** [comment]
> `Package libgdk-pixbuf-2.0-0 is not installed.`
> `sudo apt install libgdk-pixbuf2.0-0`

These are two different packages - one with and without a hyphen. It's a bit weird but that's what upstream decided. :P

**Comment by chaogamer** [comment]
so what do i do basically?

**Comment by rozniak** [comment]
`sudo apt install libgdk-pixbuf-2.0-0`

**Comment by chaogamer** [comment]
```
$ sudo apt-get install libgdk-pixbuf-2.0-0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libgdk-pixbuf-2.0-0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgdk-pixbuf-2.0-0' has no installation candidate

```

**Comment by onkoe** [comment]
Seems to be unavailable on Bookworm: https://packages.debian.org/search?keywords=libgdk-pixbuf-2.0-0

**Comment by chaogamer** [comment]
this is the error when i try to install it manually

```
sudo dpkg -i libgdk-pixbuf-2.0-0.deb
[sudo] password for winme11:          
dpkg: regarding libgdk-pixbuf-2.0-0.deb containing libgdk-pixbuf-2.0-0:amd64:
 libgdk-pixbuf-2.0-0 breaks libgdk-pixbuf2.0-0 (<< 2.40.0+dfsg-6~)
  libgdk-pixbuf2.0-0:amd64 (version 2.40.0+dfsg-3ubuntu0.4) is present and installed.
  libgdk-pixbuf2.0-0:i386 (version 2.40.0+dfsg-3ubuntu0.4) is present and installed.

dpkg: error processing archive libgdk-pixbuf-2.0-0.deb (--install):
 installing libgdk-pixbuf-2.0-0:amd64 would break existing software
Errors were encountered while processing:
 libgdk-pixbuf-2.0-0.deb
```

**Comment by onkoe** [comment]
Which distribution + version are you using? It may not provide some of Debian’s libraries. 

You can find out with `cat /etc/os-release`

**Comment by chaogamer** [comment]
```
NAME="Zorin OS"
VERSION="16.2"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 16.2"
VERSION_ID="16"
HOME_URL="https://zorin.com/os/"
SUPPORT_URL="https://help.zorin.com/"
BUG_REPORT_URL="https://zorin.com/os/feedback/"
PRIVACY_POLICY_URL="https://zorin.com/legal/privacy/"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by onkoe** [comment]
Zorin is based on Ubuntu, which seems to package `libgdk-pixbuf-2.0-0` [inside](https://launchpad.net/ubuntu/+source/gdk-pixbuf) the `gdk-pixbuf` package. Try installing it and see if it fixes your issues. :)

**Comment by chaogamer** [comment]
im confused on where to go, which package to choose? can you pick one for me?

**Comment by onkoe** [comment]
Of course. Please try running this command: `sudo apt install gdk-pixbuf`

Let me know how it works out! 🤩

**Comment by chaogamer** [comment]
```
sudo apt install gdk-pixbuf
[sudo] password for winme11:          
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gdk-pixbuf

```

also tried apt-get, same error.

**Comment by onkoe** [comment]
I see - I've found the problem! You're running Ubuntu Fossa (20.04), but the newest version of Ubuntu that provides the `libgdk-pixbuf-2.0-0` package is Ubuntu Jammy (22.04). You can see the situation [as shown on `pkgs.org`](https://pkgs.org/download/libgdk-pixbuf-2.0-0). 

Or, you know... Zorin OS 16.3 is based on Ubuntu 20.04. So it's just about the same!

If you want to use this package, you'll likely need to wait for Zorin OS 17, which should be based on Ubuntu 22.04 LTS. That's a new enough version for the package to be added to the Ubuntu repos! :)

In the meantime, you can always spin up a Debian 12 virtual machine to see how it looks. If you're feeling particularly evil today, you can also start messing with the package recipes... but that's a significant risk, both for your system and your sanity. 😌

Also, sorry for the difficulties! I only have online information because I don't use Debian or Ubuntu. Please let me know if you find out anything else!

**Comment by rozniak** [comment]
Why oh why is this one particular package like this :weary:

**Comment by chaogamer** [comment]
is there atleast still a way to get the windows xp plugins installed to the xfce4 panel?

**Comment by rozniak** [comment]
Assuming `wintc-taskband` compiled/packaged okay and you installed it, you should be able to run it and get the taskbar and everything

**Comment by chaogamer** [comment]
it's been compiled successfully
https://pastebin.com/X18JJCx3

i forgot how to package though, because now im lost as a bunch of stuff happened to my zorin os laptop randomly

**Comment by chaogamer** [comment]
also is it ok to make it where i can just install the taskband plugin like a normal xfce4 plugin?

**Comment by rozniak** [comment]
It's not a plugin, it's its own program. :stuck_out_tongue: 

```
./build.sh shell/taskband
./package.sh shell/taskband
sudo dpkg -i dpkg-out/wintc-taskband.deb
wintc-taskband &
```

**Comment by chaogamer** [comment]
this is what happens when i try to package after a fallout with zorin os

```
/home/winme11/Downloads/xfce-winxp-tc-master/shell/taskband/src/application.c:2:10: fatal error: gtk/gtk.h: No such file or directory
    2 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/wintc-taskband.dir/build.make:67: CMakeFiles/wintc-taskband.dir/src/application.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:106: CMakeFiles/wintc-taskband.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Package assembly failure!

```

**Comment by rozniak** [comment]
Run `chkdeps.sh` and it will tell you all the development dependencies you are missing

**Comment by chaogamer** [comment]
```
libxfce4windowing not available.

** (wintc-taskband:8712): WARNING **: 19:56:01.202: libxfce4windowing not available.

```

**Comment by chaogamer** [comment]
```
The following packages have unmet dependencies:

libwintc-winbrand: Depends: libgdk-pixbuf-2.0-0 but it is not installed
wintc-taskband: Depends: libgdk-pixbuf-2.0-0 but it is not installed
                Depends: libwintc-shelldpa but it is not installed
```
even if it was a warning, it still doesn't show, likely for these reasons, i tried to force install the deb because im tired of the libgdk error

**Comment by rozniak** [comment]
I'll investigate on Zorin

**Comment by rozniak** [comment]
This particular package is really confusing to me (I'm certainly no packaging expert myself).

It seems like based on what Debian's package descriptions say, the name of the package is changing? Debian hosts both names, but I guess Ubuntu have just done a clean break?

The solution mentioned on Debian's site says:

`Packages that only require the main library should depend on libgdk-pixbuf-2.0-0 | libgdk-pixbuf2.0-0.`

So I'm going to have to look into the packaging scripts here to add support for this kind of 'this or that' dependency to fix this problem. :sweat_smile:

**Comment by rozniak** [comment]
> ```
> libxfce4windowing not available.
> 
> ** (wintc-taskband:8712): WARNING **: 19:56:01.202: libxfce4windowing not available.
> ```

Oh, as an aside this can safely be ignored. The taskband attempts to identify at runtime whether you have either `libxfce4windowing` or `libwnck` so that both Wayland and X11 can be supported without needing to faff around with compile time options. It's only a problem if it can't find either, which it would log as `Critical`.

**Comment by rozniak** [comment]
FYI I am looking at fixing this dependency issue, I have a potential solution in mind

**Comment by rozniak** [comment]
@chaogamer Latest `master` should have a fix, please pull and retry

![image](https://github.com/rozniak/xfce-winxp-tc/assets/13258281/89f84dd9-1cf6-4298-81fd-1411fad07e7b)

**Comment by chaogamer** [comment]
thanks for fixing it.
i'll check it out later once im able to fix every other problem i created myself.
my zorin os laptop is basically screwed to a point im not able to run steam at all, making most of my owned games unplayable

**Comment by rozniak** [comment]
Sorry to hear that man, do you want me to keep this open for you to test ?

**Comment by rozniak** [comment]
Haven't had any issues lately - problem should be fixed
