### ISSUE TITLE
can't compile the theme on Arch Linux due to dependency errors

### ISSUE THREAD

**Issue by Curly68** [rozniak/xfce-winxp-tc#253]
When i tried to compile through the AUR, this error happened that caused to halt the process
`libgdk-pixbuf-2.0-dev|libgdk-pixbuf2.0-dev is unavailable for your distro.
Dependencies check unsatisfied or failed.`
I eventually checked the git repository itself and when i ran .chkdeps.sh the same error happened meaning that it wasn't a error on the AUR packaging's end.
The pixbuf2 library is installed on my system, although it's on another name according to how it's listed in the Arch repos "gdk-pixbuf2". Also the latest version is 2.42.10-2. Does this project depend on a older version of the library offered by slower-rolling and stable release distros like Debian`or can this be changed in some way?

**Comment by rozniak** [comment]
That package listing is intended for Debian/Ubuntu - you wouldn't happen to have `dpkg` installed would you? It might be `distid.sh` thinking you have Debian installed and thus checking against the wrong packages...

**Comment by Curly68** [comment]
i do have dpkg installed
also when i try to run the buildall.sh it fails due to the same error
`[SnugglyBun@SnugglyPC ~]$ cd /home/SnugglyBun/Documentos/winxptheme/xfce-winxp-tc/packaging
[SnugglyBun@SnugglyPC packaging]$ ./buildall.sh
Doing full system build for d6d877e.master(SnugglyBun).231209-1313 (x86_64, deb) (free)
./chkdeps.sh: línea 132: apt-cache: orden no encontrada
./chkdeps.sh: línea 132: apt-cache: orden no encontrada
libgdk-pixbuf-2.0-dev|libgdk-pixbuf2.0-dev is unavailable for your distro.
Dependencies check unsatisfied or failed.`
(btw my computer is in Spanish so sorry if you can't understand some of what it says. the spansih text pretty much says order not found i think)

**Comment by rozniak** [comment]
Yeah basically it tries to identify your distro by probing for what package manager is installed - there's probably a better way but that's how it is for now.

I'm not at home at the moment but if you have a poke around in `distid.sh` you'll see what I mean. For now if you just want to get it building you could just put
```bash
echo -n "archpkg"
exit 0
```
at the top of the script to just force it to recognise you're on Arch Linux.

I'll have to revisit it for a proper fix, perhaps by changing the order of probing (check for `pacman` first perhaps and `dpkg` last?) and maybe add an optional argument to the scripts to bypass distro identification to manually specify what you want (which may be suitable for ensuring the AUR always works).

**Comment by Curly68** [comment]
Okay with the code you sent to me it could compile thankfully :)
Thank you

**Comment by rozniak** [comment]
Glad that works for you, I'll have to sort out a proper fix soon. :grin:
