### ISSUE TITLE
Panel Issues Linux Mint

### ISSUE THREAD

**Issue by jaybaxr** [rozniak/xfce-winxp-tc#256]
First under the Panel Preferences Items the Start button and notification area selections are not showing to add. Second is the panel doesn't change properly when choosing the Windows XP Style (Blue). Everything else changes just fine but the panel. This has done the same thing in Xbuntu as well.

**Comment by rozniak** [comment]
This project no longer uses XFCE Panel, it provides its own taskbar implementation - run `wintc-taskband` to launch it.

**Comment by jaybaxr** [comment]
I ran wintc taskband in terminal and it sent these errors:

(wintc-taskband:22373): Gtk-WARNING **: 11:45:59.491: Theme parsing error: gtk.css:1072:18: 'border_color' is not a valid property name

(wintc-taskband:22373): Gtk-WARNING **: 11:45:59.493: Theme parsing error: gtk.css:1499:18: Junk at end of value for margin

(wintc-taskband:22373): Gtk-WARNING **: 11:45:59.493: Theme parsing error: gtk.css:1511:18: Junk at end of value for margin

(wintc-taskband:22373): Gtk-WARNING **: 11:45:59.493: Theme parsing error: gtk.css:1515:14: Junk at end of value for margin

(wintc-taskband:22373): Gtk-WARNING **: 11:45:59.493: Theme parsing error: gtk.css:1527:14: Junk at end of value for margin
** Message: 11:45:59.529: libxfce4windowing not available.

** (wintc-taskband:22373): WARNING **: 11:45:59.529: libxfce4windowing not available.

Thank you for your help

**Comment by rozniak** [comment]
Those are warnings rather than errors, the taskband should be working unless you see anything else? :thinking:

**Comment by jaybaxr** [comment]
Just one more thing. Everything looks and works great with the panel until I close the terminal.

**Comment by rozniak** [comment]
That is because the terminal is the parent process when you run it that way, when you close the terminal it closes the child process.

Add `wintc-taskband` to `XFCE Settings > System > Session and Startup > Application Autostart` for the taskband to launch upon login.

**Comment by jaybaxr** [comment]
It works perfect now. Thank you for your help.

**Comment by rozniak** [comment]
No problem, glad I could help. :grin:
