### ISSUE TITLE
Merry Christmas to anyone who sees!

### ISSUE THREAD

**Issue by rozniak** [rozniak/xfce-winxp-tc#258]
I don't think there's really any way of setting any like current state or anything on a repo for anyone looking so this is the next best thing.

I am off on holiday for the next 2 weeks, so I won't be around to answer any questions or do anything on the repo most likely during that time. :partying_face: 

I wish anyone that sees this a Merry Christmas and a Happy New Year! :santa: :gift:

**Comment by MrMegarich** [comment]
Merry Christmas to you too! Thanks for answering all my questions this year! I hope the next year brings good things for you and this project.

**Comment by 2000sLegacyOS** [comment]
Merry Christmas and happy new year, also I've haven't been able to install this yet... :-(

**Comment by rozniak** [comment]
I am more or less back now. :grin: 

@2000sLegacyOS Please could you open an issue with whatever problem you are having? Thanks!
