### ISSUE TITLE
Failed Build

### ISSUE THREAD

**Issue by PlanetNINE-Dev** [rozniak/xfce-winxp-tc#259]
All dependencies installed.
./build.sh: line 126 cmake command not found
no targets specified and no makefile found
failed build for base/bootvid
![Screenshot from 2023-12-19 20-30-21](https://github.com/rozniak/xfce-winxp-tc/assets/149206403/7203f67c-ec6f-4228-a2cc-bd0aeea42ad7)

**Comment by rozniak** [comment]
You have not installed all the build prerequisites - in this case (as the error says), you are missing `cmake`. Have a look at `/packaging/README.MD` and it mentions what you need.
