### ISSUE TITLE
taskband is lacking a theme

### ISSUE THREAD

**Issue by LeoTech10** [rozniak/xfce-winxp-tc#260]
The wintc-taskband application doesn't theme like the rest of the system, what did i do wrong? I compiled the theme and installed all the deb files (Maybe i missed one?) (I'm using Linux Mint)
![Istantanea_2023-12-21_09-04-39](https://github.com/rozniak/xfce-winxp-tc/assets/111436170/28e99014-2e7c-476b-a41f-d0c115e11479)

**Comment by rozniak** [comment]
I can only assume you may have applied a different theme than the one that was built from this repo? It should be called Windows XP style (Blue)

**Comment by weirdbeardgame** [comment]
I'm having the same issue in arch.

**Comment by rozniak** [comment]
Closing per no response for months
