### ISSUE TITLE
Finally build the taskband package, new issue though

### ISSUE THREAD

**Issue by chaogamer** [rozniak/xfce-winxp-tc#261]
![image](https://github.com/rozniak/xfce-winxp-tc/assets/76564608/cfd31ab3-c678-4ba6-8e68-b67c966b37c4)

something with libgtk layers failing or something, how do i fix this?

**Comment by chaogamer** [comment]
ok i had to run sudo and it now works, but where's the windows xp theme?
![image](https://github.com/rozniak/xfce-winxp-tc/assets/76564608/7d5cae99-2298-424a-9097-56b9843d036e)

**Comment by chaogamer** [comment]
ok i fixed the theme, but it's broken when running from root, how do i make it so i have to not run it from root and run it normally?

**Comment by Fabxx** [comment]
@chaogamer do you have discord? i need some help in getting this thing to work

**Comment by chaogamer** [comment]
psibtd6, but don't worry about it, it was fixed by switching to the xfce environment, though I recommended switching to reddimaond xp theme as the taskband is kinda lacking In right click feature and pfp customization.

**Comment by chaogamer** [comment]
> @chaogamer do you have discord? i need some help in getting this thing to work

Psibtd6, check comment above btw, I forgot to quote reply

**Comment by rozniak** [comment]
I don't really know why you would need to run it with `sudo` ? Do you need anything answered here ?

**Comment by rozniak** [comment]
Closing... I don't think there's any bug here?
