### ISSUE TITLE
deb packages do not add items to panel

### ISSUE THREAD

**Issue by Fabxx** [rozniak/xfce-winxp-tc#262]
Debian 12 bookworm + xfce4

 if you have wine installed the package notepad conflicts with the /usr/bin/notepad used by wine. Another problem is that when you go into the panel, you don't see the new items to add such as "start button" ecc. Here is the item search with the xp filter

![immagine](https://github.com/rozniak/xfce-winxp-tc/assets/30447649/a8a70326-7240-430f-a104-f946c564900e)

**Comment by Fabxx** [comment]
UPDATE: it was sufficient to just make a new directory and redirect the output of the deb packages, however if you have wine installed the package notepad conflicts with the /usr/bin/notepad used by wine. Another problem is that when you go into the panel, you don't see the new items to add such as "start button" ecc.
![immagine](https://github.com/rozniak/xfce-winxp-tc/assets/30447649/43dc6328-c3c9-425e-bb42-bbbb390bb30c)

**Comment by rozniak** [comment]
Answered on Discord

**Comment by jamestmartin** [comment]
> Answered on Discord

Would be nice to have the answer here, too, for other people having the same issue.

**Comment by rozniak** [comment]
@jamestmartin There are other issues open about the same thing, I think all sourced from the old YT vid from when the Start menu/taskbar were implemented as XFCE Panel plugins. The panel plugins were merged into a new program, `wintc-taskband`, in #183 . :smile:

**Comment by jamestmartin** [comment]
Yep, that's where I got it from. I didn't see in the main or packaging READMEs that I had to run a program. It works now. Thanks for the quick reply!
