### ISSUE TITLE
Build fails on debian 12

### ISSUE THREAD

**Issue by MrMegarich** [rozniak/xfce-winxp-tc#268]
I have no clue what could possibly be causing this, but whenever I run ./buildall, it spits this error at me: 

![Screenshot (22)](https://github.com/rozniak/xfce-winxp-tc/assets/95163334/c65b7ebf-9ece-46d7-87a1-190fc275c408)

![image](https://github.com/rozniak/xfce-winxp-tc/assets/95163334/18921fcc-02cf-4b17-b87e-ff50bf0fcfb6)

**Comment by MrMegarich** [comment]
sorry about the screenshots, I don't know how to install guest additions on debian

**Comment by rozniak** [comment]
Did you perhaps run with `sudo` or something before? The errors are pretty self explanatory - your user account doesn't have permission to delete stale build output.

**Comment by MrMegarich** [comment]
Yeah, I must've run sudo on it before

**Comment by MrMegarich** [comment]
I deleted the folder of the desktop, and ran git clone again, and tried running buidall again but it still gave me the same error.

**Comment by rozniak** [comment]
Check the permissions/ownership on the files it is complaining about. :stuck_out_tongue:

**Comment by MrMegarich** [comment]
I'm the owner for all of them. I checked by right clicking on the files and going to properties.

**Comment by MrMegarich** [comment]
And my access is read and write

**Comment by rozniak** [comment]
And the directory permissions are correct?

**Comment by MrMegarich** [comment]
What's a directory permission?

**Comment by rozniak** [comment]
Directories also have permissions and ownership - you must have write permission on the directory as well to be able to delete files inside it.

**Comment by MrMegarich** [comment]
I own the build folder and everything in it

**Comment by rozniak** [comment]
I would just `sudo rm -rf build` in there

**Comment by MrMegarich** [comment]
Alright

**Comment by MrMegarich** [comment]
Does that delete the build folder?

**Comment by MrMegarich** [comment]
Do I just run buildall now?

**Comment by rozniak** [comment]
Yeah, the script errors there are where it failed to delete the `build` folder before continuing to the actual build process. If you binned `build`, it should now work. You don't need `sudo` for the build stage, only for installing the outputted packages.

**Comment by MrMegarich** [comment]
It gave me the same error, I didn't run sudo ./buildall.sh or anything.

**Comment by rozniak** [comment]
I don't see how it can complain about not being able to delete the `build` directory if it has already been deleted?

**Comment by MrMegarich** [comment]
Well it is deleted

**Comment by MrMegarich** [comment]
I ran the command you gave me in packaging, I was meant to run it in there right?

**Comment by rozniak** [comment]
Oh is the error coming from `sudo rm -rf build` ? I thought you'd successfully done that already

**Comment by MrMegarich** [comment]
Oh, no that command worked fine

**Comment by MrMegarich** [comment]
I'm just asking if I was meant to run it inside packaging

**Comment by rozniak** [comment]
Well that is where the `build` folder was, so yea :stuck_out_tongue:

**Comment by MrMegarich** [comment]
yeah ofc silly question.

**Comment by MrMegarich** [comment]
could it be because I encrypted my home folder?

**Comment by MrMegarich** [comment]
ok well I re-installed the whole os and still the same error

**Comment by rozniak** [comment]
Again, I don't see how you can get an error related to the `build` folder if it doesn't exist? If you reinstalled the whole OS, and cloned down, there's no way you can get that same error.

**Comment by rozniak** [comment]
@MrMegarich Are you running any other commands other than installing packages and then `./buildall.sh` ? There must be some reason that you are receiving a permissions error - at least the script must have been run once before for the files to exist in the first place? :thinking:

**Comment by MrMegarich** [comment]
Well, both times I think I might've run ./buildall without first installing cmake

**Comment by MrMegarich** [comment]
Could that be it?

**Comment by rozniak** [comment]
I would give it another shot, and keep track of exactly what you're doing - when does the `build` folder appear, and can you delete it? The crux really is to find out what is going on with that directory, why you don't have permissions to delete the contents.

**Comment by MrMegarich** [comment]
Bro I'm so sorry for just leaving it like this and ignoring you for the past 3 months, i will close this issue now

**Comment by rozniak** [comment]
@MrMegarich No probs, hope you're doing well! :grin:
