### ISSUE TITLE
window border theme not applying

### ISSUE THREAD

**Issue by GDPlayer** [rozniak/xfce-winxp-tc#277]
on some applications the theme isnt applied
![image](https://github.com/rozniak/xfce-winxp-tc/assets/51692409/7a50516e-28bb-486b-912c-459d2eb0123a)
yes the theme is on

**Comment by rozniak** [comment]
Have you selected the theme under Window Decorations in XFCE settings? It's not a per-application setting, it should apply to all windows (except those using CSD).

**Comment by GDPlayer** [comment]
where is window decorations

**Comment by GDPlayer** [comment]
nvm it's under window manager
