### ISSUE TITLE
how do i enable logonui

### ISSUE THREAD

**Issue by GDPlayer** [rozniak/xfce-winxp-tc#278]
title
Distro: Pop!_OS 22.04

**Comment by rozniak** [comment]
Personally I edit `/etc/lightdm/lightdm.conf` - set `greeter-session=wintc-logonui` in there.

NTS maybe meant to use `update-alternatives`

**Comment by GDPlayer** [comment]
is wintc-logonui an executable? i installed it and it says command not found

**Comment by rozniak** [comment]
The executable itself is `logonui` - I'm not sure why you'd be trying to run it though, it is only meant to be launched by LightDM to provide the logon screen. That is why I mention editing `/etc/lightdm/lightdm.conf` in order to use it.

**Comment by GDPlayer** [comment]
okthx
