### ISSUE TITLE
Does apperance style no longer change look of xfce panel?

### ISSUE THREAD

**Issue by msbrookebt** [rozniak/xfce-winxp-tc#281]
Hi I am fairly new to linux so forgive me if I'm not getting certain stuff, I tried my best to follow the 'TL;DR on Building' stuff and installed all the .deb packages it created - I was also following along that old tutorial video on youtube somewhat afterwards in terms of just trying to apply the installed stuff (not actually install it in first place). I eventually figured out it was outdated because at the time of that video the panel theme changes were customizations built into the xfce panel, whereas now that panel is entirely replaced with wintc-taskband. I will be honest I quite dislike the wintc-taskband and do not want to use it because it removes things from my panel which I really do not want to be removed, however I still want my panel to have the XP theming (even if I can't actually get start menu etc anymore).
However when I select 'Windows XP Style (Blue)' in the appearance settings, while it does change theming correctly in terms of windows etc, it does not change the panel themeing much, it remains white - see pic.
![panel image real](https://github.com/rozniak/xfce-winxp-tc/assets/148040273/7ce22ab4-d7cf-4ca3-9102-44ffed91336c)
My question is basically - is this working as intended? Does the style setting no longer change the panel theme because you have to use wintc-taskband to get the correct theme now? Or should it still be changing the panel to be blue XP theming even if I am not using wintc-taskband.

**Comment by rozniak** [comment]
Yeah it is working as intended - the styles that used to point to XFCE Panel were adjusted for `wintc-taskband` as part of #183 .

`wintc-taskband` is still quite WIP, but should eventually gain all the features of the Windows XP taskbar.

**Comment by msbrookebt** [comment]
> Yeah it is working as intended - the styles that used to point to XFCE Panel were adjusted for `wintc-taskband` as part of #183 .
> 
> `wintc-taskband` is still quite WIP, but should eventually gain all the features of the Windows XP taskbar.

I see. Ah well. Thank you for confirming.

**Comment by rozniak** [comment]
BTW if there's anything that you need that the XP taskbar itself doesn't normally do, there will be custom toolbar / shell extension support in future, kind of like how you can extend XFCE Panel
