### ISSUE TITLE
[Request] Arch Linux ARM / aarch64 support

### ISSUE THREAD

**Issue by d3-X-t3r** [rozniak/xfce-winxp-tc#289]
Hi,

Not sure if this is the right place to ask, but I felt it's easier to discuss here than on the AUR comments page.

I tried modifying the PKGBUILD to target `aarch64` (to install on Arch ARM, in a Termux proot). The makepkg then fails with an error `libgdk-pixbuf-2.0-dev|libgdk-pixbuf2.0-dev is unavailable for your distro`. 

There is no `libgdk-pixbuf2.0-dev` (or similar) in the ALARM repos. Instead, I found the arm64 version on the [Debian Bookworm repos](https://debian.pkgs.org/12/debian-main-arm64/libgdk-pixbuf2.0-dev_2.40.2-2_arm64.deb.html) and installed the converted .deb using debtap. 

However, when I run makepkg again, it still complains that libgdk-pixbuf2.0-dev is unavailable. How do I check whether this really exists - or is there an easy way I can build this myself? I looked at the [gitlab source for gdk-pixbuf](https://gitlab.gnome.org/GNOME/gdk-pixbuf), but there's no indication that I'd get the -dev package by building from there.

Alternatively, is there a way I can skip building all this and just manually copy the theme files over? Thanks!

**Comment by rozniak** [comment]
This sounds like #253 - `distid.sh` tries to identify what package format to use, and `dpkg` is checked before `pacman`, so if you have `dpkg` installed, it will look for Debian/Ubuntu dependencies.

There is a workaround in that issue thread for the problem (edit `distid.sh` to always just echo `archpkg` to force Arch Linux detection).

**Comment by d3-X-t3r** [comment]
Thanks @rozniak, that worked (sort of)! I also had to modify `packaging/cmake-inc/packaging/CMakeLists.txt` to add this line at line 32:

`${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64"`

Also, regarding the `distid.sh` - a quick-fix would be to just check for `pacman` before `dpkg`, as it's more likely that an Arch user might have `dpkg` installed as opposed to a Debian user with `pacman`. :) 

With these changes, and the `PKGBUILD` amended for `aarch64`, the package installed successfully.

**Comment by rozniak** [comment]
Thanks for trying this out! I didn't know about the `aarch64` name for Arch Linux, so I'll add that in - also needs adding in `/base/bootvid/plymouth.cmake` and `/shared/winbrand/CMakeLists.txt` for the `64-Bit Edition` branding.

**Comment by rozniak** [comment]
Believe it should be fixed in this repo now - previously only checked against `armv8`, added `aarch64`
