### ISSUE TITLE
wintc-taskband's start menu opens as a window instead of a pop-up in Devuan

### ISSUE THREAD

**Issue by knightcole** [rozniak/xfce-winxp-tc#292]
I am running on Devuan Excalibur (equivalent to Debian Trixie)

I installed all the required dependencies and after building and installing the deb packages, I ran wintc-taskband and clicked the start menu, and noticed that the menu opened as a window with the name "Popup" instead of as an actual start menu like in the README screenshot. Is there a way to fix this?

![Screenshot_2024-04-06_12-44-20](https://github.com/rozniak/xfce-winxp-tc/assets/80375725/f4725b33-e2b2-4856-8abc-afe3110fdef9)

If it helps, I attached the stdout and stderr output of buildall.sh.

[buildall_output.txt](https://github.com/rozniak/xfce-winxp-tc/files/14894305/buildall_output.txt)

**Comment by rozniak** [comment]
It should hint to not use window decorations - you're not using something like gtk3-nocsd are you ?

**Comment by knightcole** [comment]
I checked for gtk3-nocsd and it came preinstalled! Removing it fixed the issue. Thanks!

![Screenshot_2024-04-06_19-19-03](https://github.com/rozniak/xfce-winxp-tc/assets/80375725/543447c9-a152-46e6-ba8b-bed22ef8e1a6)

As an aside, I think it would be useful to add an instruction to uninstall gtk3-nocsd if it's installed in the system.

**Comment by knightcole** [comment]
Interacting with certain buttons closes the program for some reason. I ran it with the terminal and clicking Documents and Computer causes this:
```
xdg-mime: file 'exo-open --launch FileManager /home/coder900/Documents' does not exist
xdg-mime: file 'exo-open --launch FileManager /' does not exist
Segmentation fault

**Comment by rozniak** [comment]
Do you have `exo-open` ? It should be part of XFCE... :thinking: 

If it's crashing because `exo-open` is missing then that is a bug I need to deal with!

**Comment by knightcole** [comment]
I have `exo-open`. When I run the command separately, it works. Maybe it's trying to interpret a command as a file?

**Comment by rozniak** [comment]
Part of that is the look up, in case it refers to a file on disk (determine file MIME, then open it with MIME handler)

It *should* be failing through that to the final 'just run the command' case though. Maybe I'll have to try spinning up a Devuan VM to have a poke

**Comment by rozniak** [comment]
I have managed to reproduce the crash on a Devuan Excalibur VM - haven't debugged yet but when I open `My Documents`, it is successful in opening Thunar, and then `wintc-taskband` segfaults afterwards.

**Comment by rozniak** [comment]
Reproducible for me when opening a new Thunar window at `/` . Crashes in GTK, after `gtk_image_set_from_pixbuf()`

Building GTK from Devuan/Debian Salsa sources to see if I can confirm if this is a GTK bug in 3.24.41-1 or if somehow the usage of GTK is wrong. Re-reading the docs I'm sure the taskband/shelldpa code is correct (maintain a reference to the pixbuf, set image (GTK adds a ref), unref ours).

**Comment by rozniak** [comment]
Screenshot of backtrace (gobject sources not shown - only GTK3/wintc)
![image](https://github.com/rozniak/xfce-winxp-tc/assets/13258281/545b96f9-bc4e-4795-a6e7-dac3c2099da9)

**Comment by rozniak** [comment]
Next steps - will need to check if this problem still occurs in latest GTK 3.24 branch upstream. If the issue persists, bisect against latest known working version of GTK 3 (whatever is latest on like Arch Linux or Alpine I guess? pretty sure those are working)

**Comment by rozniak** [comment]
Issue does not occur with the latest upstream GTK `3-24` branch. Just for confirmation I tested with the upstream GTK `3.24.41` tag, and the crash occurs there.

@knightcole Unfortunately I don't have any immediate solution to the crash, it resides in the particular version of GTK 3 currently packaged in Devuan Excalibur/Debian Trixie.

**Comment by knightcole** [comment]
I see. Still, thanks for your help regardless! And good luck on your project! (^^

**Comment by rozniak** [comment]
Not sure what the those distro branches update schedules are like, but yeah in theory whenever they update GTK 3, the crash should be resolved. :grin:
