### ISSUE TITLE
Unable to compile desktop package

### ISSUE THREAD

**Issue by windowsfan6** [rozniak/xfce-winxp-tc#299]
Distro: Linux Mint 21.3

As in title, I'm unable to compile it. I think it's related to the recently added desktop background feature.

![Przechwycenie obrazu ekranu_2024-05-11_14-10-36](https://github.com/rozniak/xfce-winxp-tc/assets/151457100/5bf3bfe7-3846-4d8f-af86-67ad4f09dd21)

**Comment by rozniak** [comment]
Oversight on my part - that parameter only gets used for debug output, so it goes unused on free builds. Added `WINTC_DEBUG_ONLY` macro for this in `comgtk`. Need to remind myself to test compile on both free and checked in future! :facepalm: 

Latest master should be fixed :grin:
