### ISSUE TITLE
[feature suggestions] a more XP like bash shell

### ISSUE THREAD

**Issue by OzzyHelix** [rozniak/xfce-winxp-tc#318]
I mostly want to give you guys stuff that can be added to the bashrc file to get the bash looking more like the XP command prompt 
first being I made a script that can be a bash alias that can replace the dir command
`alias dir="$HOME/.scripts/dir.sh"` can be added to bashrc to get the new dir command
my XPPROMPT file can be added to bashrc with `cat XPPROMPT >> ~/.bashrc`
I hope you will consider adding these items to the theme as I think it makes it better 
I even went as far as to write an install script to install the bashrc stuff for the end user

```
#!/bin/bash
# Copy the dir command to a folder in the home directory called .scripts
cp -r .scripts $HOME

# cat XPPROMPT into bashrc with warning
echo "This will add lines to your bashrc to make it look like the XP command prompt"
read -p "Are you sure you want to do this? [Y/n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cat XPPROMPT >> ~/.bashrc
fi

```
that is in the install.sh in the zip
[xp-bash.zip](https://github.com/user-attachments/files/15749311/xp-bash.zip)

![image](https://github.com/rozniak/xfce-winxp-tc/assets/29835364/3a42c1e6-c098-4da5-8c53-c100b861e32b)

![image](https://github.com/rozniak/xfce-winxp-tc/assets/29835364/fa07c715-83d7-4984-ab1f-673bc01aa731)

**Comment by OzzyHelix** [comment]
the reason I didn't make a pull request for this was because its such a small change that it didn't really feel worth it for a pull request and I could just provide the files needed to do this here and you could implement them how you want to

**Comment by rozniak** [comment]
Sorry I hadn't gotten around to replying to this, I've been off sick for a few days.

I think if the project is to include a recreation of the `cmd` shell then it would need to be a complete implementation, rather than a config for bash. Mainly because I want to avoid the problem that skins usually have that it really needs to behave the same rather than just look the same.

I appreciate the effort though! :smiley:

**Comment by OzzyHelix** [comment]
I understand I was going for looking the same not functioning the same I did put some effort in to try and make it happen tho and I guess if you decide to do a cmd style shell later on maybe this could help be the basis for it later on in any case whatever decision you decide to take I'm sure will be fine I just tried to help make it look more like XP in the CMD prompt area is all
