### ISSUE TITLE
Longhorn themes

### ISSUE THREAD

**Issue by BrickerFixer** [rozniak/xfce-winxp-tc#319]
I've just installed this pack using AUR packages, but i can't see the aero/jade/plex themes that i've seen in repository. Any way to additionally install them on the system?

**Comment by rozniak** [comment]
At the moment, those themes only provide window decorations for XFWM4 - if you want to use the decorations you can manually copy their directories into your local themes dir `~/.themes` (such that you have for instance `~/.themes/Plex/xfwm4`
