### ISSUE TITLE
Wine conflicts with wintc-notepad on Fedora

### ISSUE THREAD

**Issue by aethrvmn** [rozniak/xfce-winxp-tc#325]
When installing my fedora machine I used this project to set up the XFCE theme and after that I tried to install wine to play some games.

Running `sudo dnf install wine` returns this error

```
Error: Transaction test error:
  file /usr/bin/notepad from install of wine-common-9.5-1.fc40.noarch conflicts with file from package wintc-notepad-1.0-1.x86_64
```

I solved this by removing wintc-notepad (I use mousepad mostly anyway) but I thought you should be aware of the conflict.

**Comment by rozniak** [comment]
Bummer... thanks for the heads up, I'll have a look at changing the target filename later.
