### ISSUE TITLE
Debian Bookworm (32 Bit) - "Complete failure, bailing"

### ISSUE THREAD

**Issue by acdavit** [rozniak/xfce-winxp-tc#328]
I wanted to install this project on my ThinkPad X40 with Debian, but I couldn't build it. 

I followed the build instructions, installed all of the dependencies, and received this error at the end:

```
-- Build files have been written to: /home/david/winxp-tc/xfce-winxp-tc-master/packaging/build/themes/native
[ 25%] Built target venv-setup
[ 50%] Generating composed
Traceback (most recent call last):
  File "/home/david/winxp-tc/xfce-winxp-tc-master/tools/bldutils/bldtheme/bldtheme.py", line 6, in <module>
    from PIL import Image, ImageDraw
ModuleNotFoundError: No module named 'PIL'
make[2]: *** [CMakeFiles/resources-gtk2.dir/build.make:73: composed] Error 1
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/resources-gtk2.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Failed build for themes/native
buildall: Compile failure, bailing.
```

**Comment by toastom** [comment]
Did you make sure you have PIL? Try `pip install pillow` and then `./buildall.sh` again

**Comment by acdavit** [comment]
> Did you make sure you have PIL? Try `pip install pillow` and then `./buildall.sh` again

Jeez, apparently I don't even have pip installed since python3 didn't automatically install it. I'll try that and update you if it helps. Thanks.

**Comment by acdavit** [comment]
Update: still having the same exact issue even after installing pillow

**Comment by rozniak** [comment]
Try deleting `/tools/bldutils/bldtheme/.venv` and then run again, I think the issue is the CMake target is the actual `.venv` dir, so once it exists it won't run the `venv-setup` step again. If you bin that `.venv` dir it should re-run the target, and succeed now you have pip. 🤔

**Comment by acdavit** [comment]
Build Complete! Thanks!

Now in what order should I install those .deb files?

**Comment by rozniak** [comment]
Hmmm give these instructions a go, a bit crap I know but better than nothing for now I hope?

https://github.com/rozniak/xfce-winxp-tc/wiki/Install-from-compiled-sources#install-the-output

**Comment by acdavit** [comment]
Thanks, I just drag & dropped the .deb files into the terminal and I think it worked. GTK themes and wintc-taskband work and I'll setup the rest tomorrow.

**Comment by acdavit** [comment]
Solution: install pip and delete /tools/bldutils/bldtheme/.venv

**Comment by 1280px** [comment]
Thank you, worked on Debian 13 32 bit as well!
