### ISSUE TITLE
Installing the .deb files you get from the buildall script doesn't change the theme on Linux Mint 21.3

### ISSUE THREAD

**Issue by Tom-Dude** [rozniak/xfce-winxp-tc#330]
I'm using mint-meta-xfce on Linux Mint 21.3 (I normally use cinnamon) and after installing all of the .deb files that are outputted by the build process, I don't know how to get the project actually working. I don't see any new programs (besides Windows Explorer) and can't find anything for it in settings. Are there other steps I'm missing?

**Comment by rozniak** [comment]
The packages do not change the theme automatically - they are just installed, so you should see them under `XFCE Settings > Appearance`, `XFCE Settings > Window Manager` etc.

For the shell you basically need to replace the XFCE one by doing:
```bash
xfce4-panel --quit
xfdesktop --quit
regsvc
wintc-taskband
wintc-desktop
```

Add the latter 3 to your `XFCE Settings > Session and Startup` so the shell loads at logon... should hopefully work. 😎

**Comment by Tom-Dude** [comment]
I will try this, thank you!
