### ISSUE TITLE
How do I change bootvid on Debian 12?

### ISSUE THREAD

**Issue by MrMegarich** [rozniak/xfce-winxp-tc#336]
Got it running on Debian 12, how do I change the bootvid?

**Comment by rozniak** [comment]
It's a bit fiddly, I believe you need to:
- Add `splash` to the kernel parameters in your grub config, and `sudo update-grub2`
- Select the bootvid theme using `sudo update-alternatives --config default.plymouth`
- Regen `initramfs` by doing `sudo update-initramfs -u`

**Comment by MrMegarich** [comment]
Also what's the proper way of adding 'splash' to my grub config

**Comment by rozniak** [comment]
Sorry I sent that over my lunch break.

Have a read on the Debian wiki, for instance `plymouth-set-default-theme` is apparently for changing the theme, I thought it was `update-alternatives`. Maybe that's just for Ubuntu or something, I definitely saw it somewhere!

`splash` goes in `/etc/default/grub`  - have a look:
https://wiki.debian.org/plymouth#Configuration

**Comment by MrMegarich** [comment]
Do I type `--splash` or `-splash` or just `splash`

**Comment by rozniak** [comment]
![image](https://github.com/rozniak/xfce-winxp-tc/assets/13258281/352b96e1-2c0e-40a5-b64b-b82197179d50)

**Comment by MrMegarich** [comment]
I added the splash option and selected the theme with `sudo plymouth-set-default-theme -l` but it still shows command line stuff on boot and not the bootvid. And yes I ran `sudo plymouth-set-default-theme -R THEME` if you're curious.

**Comment by rozniak** [comment]
Did you `sudo upgrade-grub2`

**Comment by MrMegarich** [comment]
Yes.

**Comment by MrMegarich** [comment]
Hey it's been 4 days, sorry if you are busy but I still haven't been able to figure this out.

**Comment by rozniak** [comment]
I will have a play in a VM when I have a chance a bit later and get back to you, sorry mate

**Comment by rozniak** [comment]
@MrMegarich Mine worked:
```bash
vim /etc/default/grub # add splash to linux default
plymouth-set-default-theme -R bootvid
update-grub2
```

**Comment by MrMegarich** [comment]
That didn't work it still shows the command stuff on start up

**Comment by MrMegarich** [comment]
I can send you the vm if you want to have a look

**Comment by rozniak** [comment]
You will need to do some troubleshooting on your own ya know. I'll be busy with stuff irl for a couple weeks so won't really be around all that much.

All I can say is I set up a new Debian 12 VM and did the steps I said and it just worked. idk if you need to `apt install plymouth` or something silly like that or what, you'll have to investigate it your side.

**Comment by MrMegarich** [comment]
Ok
