### ISSUE TITLE
Improvements for comctl default styles and CPLs

### ISSUE THREAD

**Issue by rozniak** [rozniak/xfce-winxp-tc#339]
Fix up some more broken / unfinished styling:
- Default button box style needs tuning for non-XP themes (eg. Adwaita) - check the Run dialog for example, the margins are broken under Adwaita
- Add default margin styles for `GtkNotebook` - used in CPLs and eventually `taskmgr`
- Fix up padding/margin styles in CPLs

**Comment by rozniak** [comment]
Working on this...

I have resolved the broken appearance of the run dialog under Adwaita, this is basically because the run dialog is still very rough in how it handles the UI. It does not use resource XML or CSS for its UI, it's all hard-coded in the C from before I knew much about GTK programming. I am not fully rewriting all that in this issue, I have just fixed some stuff up enough for it to be good looking in both Adwaita and the themes in this repo.

Worth noting though that button placements vary in Windows XP... I suppose due to the manual design of the dialogs and stuff. Some have buttons spaced really wide (like the Run dialog), some have them spaced normally like the CPLs, and some have them spaced really close (like taskmgr).

I'm thinking I will just opt for normal spacing unless it's noticeably different in Windows XP, so taskmgr will have the same button spacing as the CPLs. It will just be easier and arguably nicer that way...

**Comment by rozniak** [comment]
![image](https://github.com/user-attachments/assets/6af4fd2f-b2ce-4fd2-ad51-ed63271ac969)

Should be much of an improvement over the existing lack of margin...

**Comment by rozniak** [comment]
For reference - this is what it all looks like with Adwaita. So should be compatible with other themes...

![image](https://github.com/user-attachments/assets/03dcebb9-5f7d-475b-986d-ad51f810ad72)

**Comment by MrMegarich** [comment]
That's so accurate! But one nitpick I have is the lack of the indented border around the background selection. Otherwise looks great! 😊

**Comment by MrMegarich** [comment]
![diagram](https://github.com/user-attachments/assets/4933cf71-7794-4823-801a-d1fbe2b1ec3e)

What I mean

**Comment by rozniak** [comment]
Yeah I know - it's something I need to look at later with the frames to see if it's something to apply on list boxes directly, or whether it needs an outer frame (don't want to break other programs appearances that use list boxes)

**Comment by rozniak** [comment]
@MrMegarich #353 :grin:
