### ISSUE TITLE
wintc-taskband randomly crashes

### ISSUE THREAD

**Issue by acdavit** [rozniak/xfce-winxp-tc#341]
SORRY FOR THE LOW QUALITY VIDEO!
Basically, wintc-taskband randomly crashes while using it and throws up the following text:
`Segmentation fault (core dumped)`

 I've encountered this issue both on Debian and on the Arch Linux AUR package.

https://github.com/rozniak/xfce-winxp-tc/assets/107882602/74a8673c-8145-447c-a34c-c491938b069e

**Comment by rozniak** [comment]
Is this with a recent compile? There was a segfault bug to do with the taskbar icons, but that has since been fixed. I'm trying to reproduce it here but not having much luck. :thinking:

**Comment by acdavit** [comment]
I had it installed a while back so maybe that's the issue? I'll give my system an update and update you after it finishes

**Comment by rozniak** [comment]
Compile on latest `master` and hopefully it should have been fixed

**Comment by acdavit** [comment]
Thanks, I just ran yay -Syu and it fixed the issues.

**Comment by acdavit** [comment]
Encountering the same issue once again. Updated my system yesterday and the taskband segfaults every time I close an app.

**Comment by rozniak** [comment]
Is this with a build newer than https://github.com/rozniak/xfce-winxp-tc/commit/87c5c09763ef9c085a3abc66ae1808c047cc49ef ?

**Comment by acdavit** [comment]
It should be. It's the latest AUR version with the battery and network icons and everything. Not sure how to check the build version on Arch though.

**Comment by rozniak** [comment]
I am just getting my Arch VM updated to have a look.. I'm assuming it might be something to do with the new XFCE 4.20 release. :thinking:

**Comment by rozniak** [comment]
I can't reproduce on mine - can you check what build you have under `winver` ?

**Comment by acdavit** [comment]
![image](https://github.com/user-attachments/assets/77e60546-ac7d-4318-a3e9-6c25111b9c0b)

**Comment by rozniak** [comment]
Yea your build is https://github.com/rozniak/xfce-winxp-tc/commit/c1a57641bc83c8d0d544f80cfbb1a1e9d5d4314c from Nov 12th, need to update through `yay` or however it was built thru AUR

**Comment by acdavit** [comment]
Huh, that's odd, yay shows that there are no updates available. Either something with my package manager or the package itself, I'm currently reinstalling it so I'll see how it goes.

**Comment by acdavit** [comment]
Now this is getting really weird...

![image](https://github.com/user-attachments/assets/01dd3ff9-850e-4f08-9649-c8480a3b9a7d)

**Comment by acdavit** [comment]
I completely uninstalled the whole xfce-winxp-tc-git package and reinstalled it and I think it solved my issue. Winver now works too and displays a different build number.
![image](https://github.com/user-attachments/assets/dd92bfd0-6f80-4ee4-bf61-5d2ed76e98cd)

**Comment by rozniak** [comment]
@acdavit I'm not super familiar with yay so not sure how updates normally work with it. If you're curious about new bugfixes/features you can always compare the commit hash in winver with the one shown on the master branch. 😁
