### ISSUE TITLE
closing a program causes wintc-taskband to segfault / crash

### ISSUE THREAD

**Issue by TheoCGaming** [rozniak/xfce-winxp-tc#347]
linux ver: 6.9.10
commit id: 150f0cb
installed from: AUR (r322.150f0cb-1)
graphics: NVidia (Xorg, no intel graphics)

i can't get it to produce logs, but i'm looking for a way to do that

**Comment by TheoCGaming** [comment]
[wintc-taskband-crash.txt](https://github.com/user-attachments/files/16347171/wintc-taskband-crash.txt)
[wintc-taskband-debug.txt](https://github.com/user-attachments/files/16347203/wintc-taskband-debug.txt) (opened taskband with a Thunar instance open, then closed the Thunar instance)
it only happens with programs that were never directly opened with taskband, implying that it could potentially be worked around by launching taskband at startup (e.g. through a systemd service) and using taskband to launch programs. this falls apart when other programs that have a window launch at startup, though.

**Comment by rozniak** [comment]
I'll try and have a poke around soon, potentially start of next week if I don't get any time before then. Sorry I've been mostly afk for the past two weeks with irl stuff. :postbox:

**Comment by TheoCGaming** [comment]
> Sorry I've been mostly afk for the past two weeks with irl stuff. 📮

All good! Take all the time you need.

**Comment by rozniak** [comment]
I can't reproduce this, and the error logs suggest it might be a third-party lib. Does this still occur with latest packages? :thinking:

**Comment by rozniak** [comment]
@TheoCGaming If you get a chance, are you able to check if this still happens with latest packages from Arch?

**Comment by TheoCGaming** [comment]
hello, sorry for the wait! i just tested with a fresh build and it still crashes.

**Comment by rozniak** [comment]
@TheoCGaming Latest Arch packages? Not latest in this repo cos nothing has changed in here yet

**Comment by rozniak** [comment]
I mean `pacman -Syu`

**Comment by TheoCGaming** [comment]
what's the name of the package? i'm only finding the `-git` version on the aur.

**Comment by rozniak** [comment]
I mean updating Arch Linux itself, not this repo :stuck_out_tongue:

**Comment by TheoCGaming** [comment]
oh :p 

my system is fully updated to the latest software and it's still happening.

**Comment by rozniak** [comment]
@TheoCGaming I might know why I failed to reproduce - you say this happens with windows that were *already* open prior to the taskband being launched?

**Comment by TheoCGaming** [comment]
yes

**Comment by rozniak** [comment]
Sigh I misread originally and was testing it wrong, I'll give it another go at some point

**Comment by TheoCGaming** [comment]
> Sigh I misread originally and was testing it wrong, I'll give it another go at some point

i should've done a bit more testing before i wrote the title of the post or i should've edited the title after i found out the exact cause

**Comment by rozniak** [comment]
Sorry I haven't looked at this sooner...

Able to reproduce - requires `libxfce4windowing` to be installed, close a Thunar window.

**Comment by rozniak** [comment]
Actively investigating this against `libxfce4windowing` upstream
