### ISSUE TITLE
Build script should support other package formats (or none at all)

### ISSUE THREAD

**Issue by rozniak** [rozniak/xfce-winxp-tc#35]
As title says - currently there is a single build script `build-deb.sh`. It works well enough to package the theme into a `.deb` file for easy installation on distros that use that package format, for others it's a bit of a pain currently.

Need things done:
* Support using no package manager - output the files into a nice directory structure ready for copying in, so at least users using a format not implemented by the build script can still install the files themselves (not ideal but so it works)
* Look into other popular package formats (like AUR?) and see about supporting them

**Comment by rjkilpatrick** [comment]
Have you consider adding a [Launchpad PPA](https://help.launchpad.net/Packaging/PPA) for debian-derived versions?
This would mean it's possible to install from its package manager.
Seeing as the project is FOSS, you could have [continuous integration](https://docs.travis-ci.com/user/deployment/launchpad/) pushing stable builds to the PPA automatically.

**Comment by rozniak** [comment]
Packaging systems to look at:
* `pacman`
* `yum`
* `portage`
* AUR

I'm only familiar with .deb at the moment but will keep notes here on other package managers people use that will need targeting.

**Comment by rozniak** [comment]
Also support:

- `apk` (Alpine Linux)
- `slpkg` (Slackware? From a quick Google, I'm not familiar with it at all myself)

**Comment by IntoTheVoid-900** [comment]
Also look into a copr repo (similar to PPAs for RHEL & Fedora).

**Comment by alexfeed1990** [comment]
you can convert deb packages to pacman (arch linux packages) with [debtap](https://github.com/helixarch/debtap)

**Comment by rozniak** [comment]
I am implementing some CMake stuff whilst I finish up #13 - so `make install` will work.

debtap might be a workaround for now, but I will update progress on improving the build under #140 :grin:

**Comment by rozniak** [comment]
Build system improvements made this much more feasible / quicker to implement.

Separate issues for each package manager
- Arch Linux (`pacman`) - #182  (almost done as of writing, testing)
- Alpine Linux (`apk`) - #198 
- Gentoo Linux (`portage`) - #200 
- Red Hat/CentOS/Fedora (`dnf`) - #197 
- Slackware (`slpkg`) - #199 

Will target (ideally) any system with XFCE going forward
