### ISSUE TITLE
Idea: fork thunar and  make it more like explorer

### ISSUE THREAD

**Issue by blue-devil-93** [rozniak/xfce-winxp-tc#354]
![cabinet-screenshot](https://github.com/user-attachments/assets/04eb4160-959c-44b9-9a64-51df6a041695)
I did rename thunar to cabinet with the mate porting scripts. 
Then i did use poe.com claude sonnet ai model to generate a patch for the menubar. just an idea but such an approach might be easier than rewrite explorer from scratch...

Your taskband-tc runs- pnce you get the favorites thing working it might be great however at the moment i stick to xfce defaults. 

Label this issue as feature request or Suggestion  if you want to.

**Comment by rozniak** [comment]
I think I've been suggested this sort of thing a few times.. Thunar is very different from Windows Explorer other than really the fact that both are file managers. From my pov it would take more effort to mould Thunar into Explorer than it would to write Explorer from scratch.

I do poke around the source to XFCE components for references on how certain things are done, like gvfs. It just doesn't make much sense to fork the entire thing though.
