### ISSUE TITLE
How do I change version

### ISSUE THREAD

**Issue by MrMegarich** [rozniak/xfce-winxp-tc#364]
How to I turn it into windows xp home for example? what are the commands?

**Comment by rozniak** [comment]
Pass the `-s` switch when you run `buildall.sh` , for instance `./buildall.sh -s xpclient-per` for Windows XP Home Edition.

The full list of SKUs are here: https://github.com/rozniak/xfce-winxp-tc/blob/master/packaging/cmake-inc/common/CMakeLists.txt#L44

**Comment by MrMegarich** [comment]
Thanks
