### ISSUE TITLE
Status Report

### ISSUE THREAD

**Issue by MrMegarich** [rozniak/xfce-winxp-tc#365]
I don't mean to sound entitled, but I would like to know what you are currently working on. 😊

**Comment by rozniak** [comment]
I will resume next week and finish off #8 and continue with the themes. Been busy with life stuff so it has been on pause for a bit. :stuck_out_tongue:

**Comment by MrMegarich** [comment]
All good I was just wondering!

**Comment by rozniak** [comment]
Also there is this page on the Wiki: https://github.com/rozniak/xfce-winxp-tc/wiki/Project-progress-and-status

**Comment by MrMegarich** [comment]
Thx
