### ISSUE TITLE
lock screen

### ISSUE THREAD

**Issue by PoPCaT6800** [rozniak/xfce-winxp-tc#375]
Whenever i close my device (it's a laptop), even though I set up the lock screen using the instructions, it does not work, instead showing a window with the error "none of the screen lock tools ran successfully, so the screen will not be locked". i installed with the arch package.

**Comment by rozniak** [comment]
Lock screen... do you mean the LightDM greeter, or something else?

**Comment by PoPCaT6800** [comment]
Yes, i was refferring to the lightDM greeter. I set the greeter-session to wintc-logonui, but it still shows the xfce logon screen when i turn on my computer

**Comment by rozniak** [comment]
Perhaps it's because you have the `greeter-session=wintc-logonui` too high in the config file. Try moving it underneath `#greeter-session=example-gtk-gnome` so that it falls under the `[Seat:*]` section. :thinking:

**Comment by PoPCaT6800** [comment]
this did fix the initial issue, however the lock screen accounts section contained numerous package names including systemd-coredump and git along with my user account name.

**Comment by rozniak** [comment]
I'm not really sure what you mean?

**Comment by PoPCaT6800** [comment]
i couldn't really find another way to put it into words so here's a video of my problem. the scrolling continues for a while with my name in the middle of the list.
[](https://drive.google.com/file/d/1OIsd7tLtQ3kQioQFHdT8MKuGOtlWYCh-/view?usp=sharing) (it was too big for github)

**Comment by rozniak** [comment]
Hm... well the actual user list that displays there comes from LightDM (it calls `lightdm_user_list_get_users()` to populate that list). I've not come across the same problem before... out of curiosity, do you have `AccountsService` installed? I did try to do a bit of searching to figure out how LightDM distinguishes between an actual human's account vs. a service account, I think it relies on `AccountsService` to work correctly, though I don't know for sure.

BTW what screen resolution is that? The list shouldn't be appearing so tiny either, that is something I need to fix.

**Comment by PoPCaT6800** [comment]
installing accountsservice completely fixed that issue. only my account shows up now. I am using a screen resolution of 1366x768 (i know its weird). This lock screen does still not work when i close my lid, only when i restart lightdm or restart my pc, when i lock it by closing it comes up with the previous error.

**Comment by rozniak** [comment]
I don't think the greeter has any impact on that message. Does `xflock4` work when you run it? If so, perhaps try manually setting that under `Settings Editor > xfce4-session > general > LockCommand`

**Comment by PoPCaT6800** [comment]
xflock4 did not have an affect when i ran it, but i added it to the argument as there was nothing in it's place. closing the lid does not do anything now.

**Comment by rozniak** [comment]
Have you got `light-locker` installed?

**Comment by PoPCaT6800** [comment]
i installed light locker and restarted lightdm, and now it seems to be fixed! I can't thank you enough for getting back to me so quick and helping me out, i really appreciate it!
