### ISSUE TITLE
Flesh out icon theme and add packaging script

### ISSUE THREAD

**Issue by rozniak** [rozniak/xfce-winxp-tc#72]
The basic icons are there, it is worth fleshing them out with good icon coverage and a packaging script akin to the cursors script.

**Comment by rozniak** [comment]
There is now an icon packaging script in `feat-72`, `packicon.sh`.

The idea is basically the same as cursors, all the real icons are placed under `/usr/share/icons/<theme>/res`, and the subdirectories like `16x16/apps/firefox.png` are just symlinks pointing to the real icons. These symlinks are made via the `mappings` file similar to cursors.

**Comment by rozniak** [comment]
Still working on this...

I have added a bunch more icons, mostly for MIME types - will work on the other freedesktop stuff tomorrow (like devices etc.):
![image](https://user-images.githubusercontent.com/13258281/129985359-b0ee6f7e-d910-45ce-8943-820b4beb4bf7.png)

Here's the Start menu plugin folder with these icons:
![image](https://user-images.githubusercontent.com/13258281/129985379-2c7fbea8-6f48-4b0f-a2f3-3208cb365a65.png)

There is a `todo.txt` with notes on things that need fixing / icons that need generating.

**Comment by rozniak** [comment]
Small update on this, I worked to extract icons from Office 2007's interface using the ImageMso stuff from old - took some time to get it to work since the instructions and libs themselves are so out of date. Did get it to work and now have transparent UI icons in 16x16 and 32x32. When I get some time I will sort these out for toolbar icons and stuff.

**Comment by VNGamerGit** [comment]
Got this after switching to the icon theme:
![Screenshot_2021-09-30_06-07-39](https://user-images.githubusercontent.com/61623835/135360741-74d50396-f919-485c-8766-d6c267f67d4e.png)
![Screenshot_2021-09-30_06-08-36](https://user-images.githubusercontent.com/61623835/135360743-e9695a30-dd8a-434b-9dce-e0d393f4624b.png)
The dosdevices and drive_c folders (shown in the screenshot above) should be using the folder icon, but it somehow use the same icon as the files' icon. Same thing happened to other folders

**Comment by rozniak** [comment]
That's weird considering that isn't even the files icon that's in the theme... I will have to test it on that platform and get back to you, thanks for the report. :+1:
