### ISSUE TITLE
Implement winver application

### ISSUE THREAD

**Issue by rozniak** [rozniak/xfce-winxp-tc#74]
Would be cool to have a little 'winver' program, not a 'necessity' but it makes for good screenshots. :wink:

**Comment by rozniak** [comment]
Pretty much done, reckon I'll tidy the code a bit and then merge.
![image](https://user-images.githubusercontent.com/13258281/131224927-64459ddf-6890-44ae-8ed1-766ef3ae9ef7.png)

**Comment by rozniak** [comment]
Though might want some window hints to hide the minimise button and the icon if possible...

**Comment by rozniak** [comment]
And currently uses just the x64 banner... would be cool to have one that said `Professional Linux Edition` or something?

**Comment by BoQsc** [comment]
![image](https://user-images.githubusercontent.com/21064622/131227213-28c5ae82-c67f-431e-b566-f7c188fcf265.png)
Font: http://www.publicdomainfiles.com/show_file.php?id=13486239291657
Logo: https://pixabay.com/vectors/penguin-linux-tux-avatar-cartoon-4871045/
Source File: [penguin-4871045_640.zip](https://github.com/rozniak/xfce-winxp-tc/files/7071234/penguin-4871045_640.zip)


License: Public Domain or Creative Commons.
Price: Free

Talent: None
Program: GIMP

**Comment by rozniak** [comment]
Could make tux an option? I'm going to merge winver as is and have a separate issue for banner(s).
