### ISSUE TITLE
Implement sound volume indicator / levels in notification area

### ISSUE THREAD

**Issue by rozniak** [rozniak/xfce-winxp-tc#76]
Need to add the sound volume icon into the notification area as it is in Windows XP. When clicked should open a simple meter for managing the primary output device's volume level.

Think it also needs to have a right-click menu item for opening a full fledged volume management dialog - whether to implement that is in this feature depends if it already exists and can be called to.

Refer to pulse audio XFCE plugin for how to adjust volume I suppose.

**Comment by rozniak** [comment]
Note that with regard to #94 , when the user changes their volume, the `audio-volume-change` sound should be played. The sound theme sets this to the 'ding' noise, so it should be possible to replicate the exact behaviour of the volume slider from Windows XP.

**Comment by toprak** [comment]
ohhhhh sorry for asking a useless question

**Comment by rozniak** [comment]
I am playing around with learning the PulseAudio API via the docs and XFCE's PA plugin in `feat-snd`
![image](https://github.com/rozniak/xfce-winxp-tc/assets/13258281/feac7e3b-b4b2-4f1a-ae41-e40eb95ce991)

**Comment by rozniak** [comment]
`feat-snd` merged, going to start working on the volume icon now

**Comment by rozniak** [comment]
![image](https://github.com/rozniak/xfce-winxp-tc/assets/13258281/53612cf3-5599-481b-afb8-4688b8cba500)

Notif icon test is coming together

**Comment by rozniak** [comment]
The volume icon is one of the last things I consider a 'blocker' really from the project being 'usable' since it's a bit crap having to go through `pavucontrol` all the time!

> so being able to see icons like battery/volume/wifi was pretty important

The others are on my mind - battery I think it's possible to use `upower` or query it directly under `/dev`? And WiFi/network I was thinking of supporting that via NetworkManager (though like the volume control, this will be through an abstraction layer so that the project isn't too tightly coupled with any particular backend)

**Comment by rozniak** [comment]
Getting `libwintc-sndapi` started - next step will be to enum sinks and sort out the actual volume management
![image](https://github.com/rozniak/xfce-winxp-tc/assets/13258281/8893276f-9eb6-4379-902c-5475d707f0a8)
