### ISSUE TITLE
Does not work on any other Debian/Ubuntu-based distros other than Debian

### ISSUE THREAD

**Issue by VNGamerGit** [rozniak/xfce-winxp-tc#79]
I tried installing this theme on XFCE Desktop Environment + Zorin OS 16 Core (Debian/Ubuntu-based), and other than the windows borders (if you do not know what I mean, look at the first screenshot), nothing seem to change at all (look at the second one down below)
![Screenshot_2021-09-28_14-17-38](https://user-images.githubusercontent.com/61623835/135041165-1f5b679c-4436-496d-aaf9-2abbd1104988.png)

![Screenshot_2021-09-28_14-18-18](https://user-images.githubusercontent.com/61623835/135041267-e2a795b2-18e1-466a-a42c-c71c33290a3e.png)

**Comment by rozniak** [comment]
I'll install Zorin and have a look when I get a chance.

I don't know if this applies to Zorin but usually in XFCE the window manager (XFWM4) and system theme (GTK) are in separate settings so you have to select Luna in both. I don't know if it's as simple as that but I thought I'd mention it just in case. 😃

**Comment by VNGamerGit** [comment]
> I'll install Zorin and have a look when I get a chance.
> 
> I don't know if this applies to Zorin but usually in XFCE the window manager (XFWM4) and system theme (GTK) are in separate settings so you have to select Luna in both. I don't know if it's as simple as that but I thought I'd mention it just in case. 😃

Hey, can you try other Debian/Ubuntu-based distros? The installation guide and file seems to be targeted towards Debian only, not Debian/Ubuntu-based distros

**Comment by rozniak** [comment]
Yeah the README needs updating + work done on packaging for other distros etc.

Does the Luna theme not appear under the Appearance settings in XFCE?

**Comment by VNGamerGit** [comment]
> Yeah the README needs updating + work done on packaging for other distros etc.
> 
> Does the Luna theme not appear under the Appearance settings in XFCE?

it does appear under the Appearance settings, but not the GTK/Icons/Cursors menu for some reason

**Comment by rozniak** [comment]
Huh, the theme setting under Appearance should set the GTK theme, does it not do anything?

As for icons/cursors, they have their own packaging scripts at the moment.

For cursors, use the `packcurs.sh` script under `/packaging/deb/cursors` to generate a .deb file for each cursor theme. There's only "standard" with and without pointer shadows currently. So use `./packcurs.sh no-shadow/standard shadow/standard` to generate the packages then you can install them.

For icons, they're not totally done yet but you can checkout the `feat-72` branch and there should be `packicon.sh` under `/packaging/deb/icons`. Again can generate the icon theme package by issuing `./packicon.sh luna` and then you can install the deb it outputs.

**Comment by VNGamerGit** [comment]
> Huh, the theme setting under Appearance should set the GTK theme, does it not do anything?
> 
> As for icons/cursors, they have their own packaging scripts at the moment.
> 
> For cursors, use the `packcurs.sh` script under `/packaging/deb/cursors` to generate a .deb file for each cursor theme. There's only "standard" with and without pointer shadows currently. So use `./packcurs.sh no-shadow/standard shadow/standard` to generate the packages then you can install them.
> 
> For icons, they're not totally done yet but you can checkout the `feat-72` branch and there should be `packicon.sh` under `/packaging/deb/icons`. Again can generate the icon theme package by issuing `./packicon.sh luna` and then you can install the deb it outputs.

The theme does not appear in Appearance, and it only appears in the windows manager menu

**Comment by VNGamerGit** [comment]
> For cursors, use the `packcurs.sh` script under `/packaging/deb/cursors` to generate a .deb file for each cursor theme. There's only "standard" with and without pointer shadows currently. So use `./packcurs.sh no-shadow/standard shadow/standard` to generate the packages then you can install them.
Got the `You are missing package: rename` error while running the command you sent, help for this?
> For icons, they're not totally done yet but you can checkout the `feat-72` branch and there should be `packicon.sh` under `/packaging/deb/icons`. Again can generate the icon theme package by issuing `./packicon.sh luna` and then you can install the deb it outputs.
Huh, they're actually not done. Anyway, the icon pack somehow changes the folder icons into the same icon as the files, which is confusing.

**Comment by rozniak** [comment]
> Got the You are missing package: rename error while running the command you sent, help for this?

That'll be due to this - the script uses `dpkg` to check if required packages are installed:
https://github.com/rozniak/xfce-winxp-tc/blob/master/packaging/deb/cursors/packcurs.sh#L35

> Huh, they're actually not done. Anyway, the icon pack somehow changes the folder icons into the same icon as the files, which is confusing, even though there's actually icons for folders in the icons folder

Can you post pics on #72 ?

**Comment by VNGamerGit** [comment]
> > Huh, they're actually not done. Anyway, the icon pack somehow changes the folder icons into the same icon as the files, which is confusing, even though there's actually icons for folders in the icons folder
> 
> Can you post pics on #72 ?

Posted. Now, what about this bug/issue?

**Comment by rozniak** [comment]
Do you use `dpkg` ?

**Comment by VNGamerGit** [comment]
> Do you use `dpkg` ?
> 
> EDIT: Missed your comments regarding the missing theme under Appearance... the script puts it under `gtk-3.0`, I have seen other themes specifically use a directory called `gtk-3.24`. Might need a symlink or something... perhaps you could compare the Luna theme under `/usr/share/themes` with another one in there that works?

So you want me to compare the Luna theme in this system (that doesn't work) with the one that works?

**Comment by rozniak** [comment]
Yeah like in the file system, Luna should have `gtk-3.0` in there with `gtk.css`, ould be curious to know if it needs to be more specific or something.

**Comment by rozniak** [comment]
Sorry for the wait, just setting up a Zorin in a VM to have a play from here.

**Comment by rozniak** [comment]
@VNGamerGit  I just tried it and Luna is under Appearance as expected - you not seeing this on your install?

![image](https://user-images.githubusercontent.com/13258281/136071269-586ec4a1-51f7-489e-8178-a913410fad8a.png)

**Comment by VNGamerGit** [comment]
> @VNGamerGit  I just tried it and Luna is under Appearance as expected - you not seeing this on your install?
> 
> ![image](https://user-images.githubusercontent.com/13258281/136071269-586ec4a1-51f7-489e-8178-a913410fad8a.png)
> 

Yeah, seems like so. Sorry for not replying to your last reply about the .css file, was busy. But anyway, if it does not appear, can I just copy the files into the themes folder in /usr/share?

**Comment by rozniak** [comment]
FYI guys once #85 is done this shouldn't be as much of a problem. I'm writing up documentation for everything now, and I have replaced the crappy old packaging script for the theme with a new one that checks these package dependencies so you hopefully won't be left in the dark.

Working in `feat-85` at the moment, there will be packaging scripts for everything (including the forked XFCE stuff). `deb` targeted at first, I will do some thorough testing on some of the downstream Debian-based distros. :grin:

**Comment by rozniak** [comment]
Closing this as I don't think it requires any further support and the recent documentation/packaging updates in #85 should prevent similar confusion in future.
