### ISSUE TITLE
Support opening the Start menu with Super key (Windows key)

### ISSUE THREAD

**Issue by rozniak** [rozniak/xfce-winxp-tc#86]
There should be the ability to bind opening the Start menu to the Super/Windows key.

I believe in XFCE it has a separate application that somehow opens the applications menu, perhaps this could be looked into to see how to implement that for the Start menu.

**Comment by IntoTheVoid-900** [comment]
If there is a command to open the start menu, you can bind it to the Windows button easily in Settings/Keyboard/Application Shortcuts.

**Comment by rozniak** [comment]
There is no command currently, that is the problem. :stuck_out_tongue:

**Comment by rozniak** [comment]
This could probably be handled by taking a command line argument in the `GtkApplication` to toggle the Start menu on the running instance without too much effort.

**Comment by rozniak** [comment]
Have added `--start` to `wintc-taskband`, just working on some behavioural changes (since repeatedly pressing it is buggy).

Will need to add configuration notes, because simply binding `Super` to `wintc-taskband --start` in XFCE will not get the desired results - it will block `Super+R` etc. so must use `xcape` instead.

Bind `wintc-taskband --start` to `Alt+F1` (replace popup XFCE app menu) and do `xcape -e 'Super_L=Alt_L|F1`
